### ISSUE TITLE
NPM install fails

### ISSUE THREAD

**Issue by Yatekii** [ProtonMail/WebClients#1]
I tried to install the ProtonMail Webinterface.
Sadly when I do: sudo npm install I always get:

`git clone --template=/root/.npm/_git-remotes/_templates --mirror ssh://git@github.com/bartbutler/angular-gettext-tools.git /root/.npm/_git-remotes/ssh-git-github-com-bartbutler-angular-gettext-tools-git-c40c6a4`

I tried changing this to https:// in the package.json since manual https checkout works but ssh:// does not.  Sadly it still tries using ssh ...

So I just uncommented that package and it installed just fine.

Now I do: npm start and this results in the following:

```
> protonmail-web@ start /var/www/mail.yatekii.ch/WebClient
> grunt watch --api=dev

Running "notify_hooks" task

Running "ngconstant:dev" (ngconstant) task
Creating module proton.config at src/app/config.js...OK
Warning: Task "nggettext_extract" not found. Use --force to continue.

Aborted due to warnings.

npm ERR! Linux 4.1.15-gentoo-r1-xxxx-grs-ipv6-64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! node v0.12.6
npm ERR! npm  v2.11.2
npm ERR! code ELIFECYCLE
npm ERR! protonmail-web@ start: `grunt watch --api=dev`
npm ERR! Exit status 3
npm ERR! 
npm ERR! Failed at the protonmail-web@ start script 'grunt watch --api=dev'.
npm ERR! This is most likely a problem with the protonmail-web package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     grunt watch --api=dev
npm ERR! You can get their info via:
npm ERR!     npm owner ls protonmail-web
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /var/www/mail.yatekii.ch/WebClient/npm-debug.log
```

And here is a cat of the .log:

```
nebuchadnezar WebClient # cat /var/www/mail.yatekii.ch/WebClient/npm-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@2.11.2
3 info using node@v0.12.6
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart protonmail-web@
6 info start protonmail-web@
7 verbose unsafe-perm in lifecycle true
8 info protonmail-web@ Failed to exec start script
9 verbose stack Error: protonmail-web@ start: `grunt watch --api=dev`
9 verbose stack Exit status 3
9 verbose stack     at EventEmitter.<anonymous> (/usr/lib64/node_modules/npm/lib/utils/lifecycle.js:213:16)
9 verbose stack     at EventEmitter.emit (events.js:110:17)
9 verbose stack     at ChildProcess.<anonymous> (/usr/lib64/node_modules/npm/lib/utils/spawn.js:24:14)
9 verbose stack     at ChildProcess.emit (events.js:110:17)
9 verbose stack     at maybeClose (child_process.js:1015:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
10 verbose pkgid protonmail-web@
11 verbose cwd /var/www/mail.yatekii.ch/WebClient
12 error Linux 4.1.15-gentoo-r1-xxxx-grs-ipv6-64
13 error argv "/usr/bin/node" "/usr/bin/npm" "start"
14 error node v0.12.6
15 error npm  v2.11.2
16 error code ELIFECYCLE
17 error protonmail-web@ start: `grunt watch --api=dev`
17 error Exit status 3
18 error Failed at the protonmail-web@ start script 'grunt watch --api=dev'.
18 error This is most likely a problem with the protonmail-web package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     grunt watch --api=dev
18 error You can get their info via:
18 error     npm owner ls protonmail-web
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]
```

So I actually have no clue what fails. Appart from node being the biggest mess I have ever seen ;)

I hope I am allowed to ask her :S

Thanks for any help!

**Comment by emersion** [comment]
The `npm start` fails because the package `angular-gettext-tools` is missing.

Have you setup a SSH key for your account? When you replaced `ssh` by `https`, did you just replaced by hand or did you take the right HTTPS URL from https://github.com/bartbutler/angular-gettext-tools?

**Comment by Yatekii** [comment]
No I used: https://github.com/bartbutler/grunt-angular-gettext. That is the module that fails to clone, not the one you mentioned. Except it's the same. Then it is wrong in the package.json.

And yes I have a key for my account but I am not sure if that works for not-owned repos ;)

**Comment by emersion** [comment]
No, it's because https://github.com/bartbutler/grunt-angular-gettext depends on the ssh version of https://github.com/bartbutler/angular-gettext-tools. So maybe adding https://github.com/bartbutler/angular-gettext-tools as an https dependency can solve you problem? If not, just add an ssh key to your Github account.

**Comment by Yatekii** [comment]
Ohh, I see, thanks a lot! It installed everything fine now :)

Unfortunately I now get this:

```
nebuchadnezar WebClient # npm start


> protonmail-web@ start /var/www/mail.yatekii.ch/WebClient
> grunt watch --api=dev

Running "notify_hooks" task

Running "ngconstant:dev" (ngconstant) task
Creating module proton.config at src/app/config.js...OK

Running "clean:build" (clean) task
>> 0 paths cleaned.

Running "nggettext_extract:pot" (nggettext_extract) task

Running "nggettext_compile:all" (nggettext_compile) task

Running "html2js:app" (html2js) task
Successfully converted 107 html templates to js.

Running "sass:build" (sass) task

Running "concat:build_css" (concat) task

Running "copy:build_app_assets" (copy) task
Created 16 directories, copied 190 files

Running "copy:build_appjs" (copy) task
Copied 102 files

Running "copy:build_vendorjs" (copy) task
Warning: Unable to read "vendor/jquery/dist/jquery.js" file (Error code: ENOENT). Use --force to continue.

Aborted due to warnings.

npm ERR! Linux 4.1.15-gentoo-r1-xxxx-grs-ipv6-64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! node v0.12.6
npm ERR! npm  v2.11.2
npm ERR! code ELIFECYCLE
npm ERR! protonmail-web@ start: `grunt watch --api=dev`
npm ERR! Exit status 3
npm ERR! 
npm ERR! Failed at the protonmail-web@ start script 'grunt watch --api=dev'.
npm ERR! This is most likely a problem with the protonmail-web package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     grunt watch --api=dev
npm ERR! You can get their info via:
npm ERR!     npm owner ls protonmail-web
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /var/www/mail.yatekii.ch/WebClient/npm-debug.log
```

 npm-debug.log:

```
nebuchadnezar WebClient # cat /var/www/mail.yatekii.ch/WebClient/npm-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@2.11.2
3 info using node@v0.12.6
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart protonmail-web@
6 info start protonmail-web@
7 verbose unsafe-perm in lifecycle true
8 info protonmail-web@ Failed to exec start script
9 verbose stack Error: protonmail-web@ start: `grunt watch --api=dev`
9 verbose stack Exit status 3
9 verbose stack     at EventEmitter.<anonymous> (/usr/lib64/node_modules/npm/lib/utils/lifecycle.js:213:16)
9 verbose stack     at EventEmitter.emit (events.js:110:17)
9 verbose stack     at ChildProcess.<anonymous> (/usr/lib64/node_modules/npm/lib/utils/spawn.js:24:14)
9 verbose stack     at ChildProcess.emit (events.js:110:17)
9 verbose stack     at maybeClose (child_process.js:1015:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
10 verbose pkgid protonmail-web@
11 verbose cwd /var/www/mail.yatekii.ch/WebClient
12 error Linux 4.1.15-gentoo-r1-xxxx-grs-ipv6-64
13 error argv "/usr/bin/node" "/usr/bin/npm" "start"
14 error node v0.12.6
15 error npm  v2.11.2
16 error code ELIFECYCLE
17 error protonmail-web@ start: `grunt watch --api=dev`
17 error Exit status 3
18 error Failed at the protonmail-web@ start script 'grunt watch --api=dev'.
18 error This is most likely a problem with the protonmail-web package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     grunt watch --api=dev
18 error You can get their info via:
18 error     npm owner ls protonmail-web
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]
```

I am not quite sure if I am really that dumb or if npm is really non-verbose :S

**Comment by bartbutler** [comment]
We should fix the dependency to be ssh (or https I guess) everywhere. Feel free @emersion :)

**Comment by emersion** [comment]
@Yatekii The error here is: `Warning: Unable to read "vendor/jquery/dist/jquery.js" file (Error code: ENOENT). Use --force to continue.`. Can you try to run `node_modules/.bin/bower install`? Normally this step is executed automatically right after `npm install`, but it seems that it's not the case for you.

@bartbutler Yes, since we don't need write permissions to clone these public repos, https is better as it doesn't require any authentication.

**Comment by Yatekii** [comment]
@emersion I guess it was because bower doesn't like the sudo I put in sudo npm install ;) There was some hint how to fix it; guess I will read that later :)

The script now ends with those four lines and then chills out:

```
Running "connect:watch" (connect) task
Started connect web server on http://localhost:8080

Running "delta" task
Waiting...
```

When I load that page I just get the page source as the html body but not actually a rendered page ... will have a look at my firewall and nginx relay config :)

EDIT: Nginx and FW seem to be ok ... you can have a look at the troubles here: https://mail.yatekii.ch/ (yes yes, the certi was ripped from another subdomain I have (will do that after I get the client running))

Thanks a lot for your help!

**Comment by Yatekii** [comment]
@emersion I guess it was because bower disliked sudo from sudo npm install ;) We'll fix that later. For now the Webserver seems to run and the nginx-forward works too. Sadly I don't see the rendered page but It's source as the body ... have a look: https://mail.yatekii.ch/ (yes yes, the certi was ripped from another subdomain I have (will do that after I get the client running))

**Comment by emersion** [comment]
When I go to https://mail.yatekii.ch/ I get a rendered page.

Note that you can't use this client as a webmail without a server - and this repo doesn't include a real server. That's why you get "Sorry our server is down" when you try to login.

**Comment by Yatekii** [comment]
http://noah.wapple.ch/screens/Screen%20Shot%202016-06-12%20at%2018.44.46.png

Here is a Screenshot of what I see in Chrome. In Safari it even downloads the .html file ... Firefox is the same problem. So I have no clue how you can get a rendered page ...
Mates of mine tell me the same behvaior on their systems :(

Also, I already have a server backend. I just want a proper webclient for when I have no laptop with me :) And ProtonMail has the only sane one in both design and functionality as far as I am informed.

Also sorry for commenting on this again :(

**Comment by emersion** [comment]
How do you plan to connect the webclient with your server? You can't just install the webclient and expect it to work with your IMAP/SMTP server - you need an API server between.

**Comment by Yatekii** [comment]
... lol, I was talking about the WebUI not rendering. To which you responded it renders great for you. Which it doesn't. And now you are talking about IMAP/SMTP?
Anyways, I know it's an nginx issue which I can fix myself :) Thanks for your help!

**Comment by emersion** [comment]
Just wanted to make sure you know that you can't use the webclient as is to read your personal email. ;-)
