### ISSUE TITLE
Feature request: Always add files as attachments

### ISSUE THREAD

**Issue by arunsathiya** [ProtonMail/WebClients#100]
## Current setup of how adding files to email works

When I try to upload a few files to the ProtonMail email editor, I am asked to choose on how to upload these files - `Inline` or as `Attachments`

There is no way to force ProtonMail web client to always treat such uploads as `Attachments`, as opposed to being `Inline`

## What I am suggesting here

- It would be a good idea to have an option on ProtonMail settings for one to enable uploading of files as `Attachments` all the time.
- Or, it would be a good idea to have a hotkey like Shift key that treats the files being uploaded as `Attachments`

**Comment by arunsathiya** [comment]
Is this functionality available now, or closed as `wontfix`?

**Comment by mmso** [comment]
@arunsathiya feature requests are welcome at https://protonmail.uservoice.com/forums/284483-protonmail
