### ISSUE TITLE
Mailto links not supported in firefox

### ISSUE THREAD

**Issue by ADepic** [ProtonMail/WebClients#101]
## Expected Behavior
Firefox shows a small pop-up in top right hand corner saying "Add protonmail as a mailto application"

## Actual Behavior
No such popup

## Steps to Reproduce the Problem

  1. Open protonmail.com
  2. Login
  3. Try and search for firefox popup to add as mailto.

## Specifications

  - Version:
  - Platform: FIrefox
  - URL: Protonmail.com

P.S Mailto links in firefox are supported by tutanota:

https://mail.tutanota.com/login?requestedPath=%2Fmailto%23url%3Dmailto%253Atnp%2540schabi.org

You can see mailto link in the browser url. For more privacy maybe you could obfuscate the url too

**Comment by ShalokShalom** [comment]
Is this supposed to work now?

**Comment by KiaraGrouwstra** [comment]
prior discussion: https://github.com/Noitidart/MailtoWebmails/issues/39

**Comment by chorliya** [comment]
> 
> P.S Mailto links in firefox are supported by tutanota:
> 
Here's that URL, properly displayed, thanks for the post as this is needed!..:) 

`https://mail.tutanota.com/login?requestedPath=/mailto#url=mailto:tnp@schabi.org`

**Comment by chorliya** [comment]
Btw., a custom _mailto_ string can't be added through Firefox interface, it looks for an application only - on manual edit. Screenshots attached.
![2020-02-11_23-28-05](https://user-images.githubusercontent.com/59001039/74287296-8773e380-4d21-11ea-9758-b9dd0c15e052.png)

![2020-02-11_23-28-20](https://user-images.githubusercontent.com/59001039/74287309-8f338800-4d21-11ea-9b8f-3082b44b9b4f.png)

![2020-02-11_23-29-31](https://user-images.githubusercontent.com/59001039/74287318-92c70f00-4d21-11ea-9568-a99dbad54377.png)

**Comment by ephraim71** [comment]
Hi, how to make this work?

**Comment by romulasry** [comment]
Added the bug to Mozilla's Bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1683731

**Comment by Hritik14** [comment]
I believe this happens because protonmail logs you out even if you change tabs /  close, reopen tabs. I found [this 4 year old thread](https://www.reddit.com/r/ProtonMail/comments/5hwtzs/how_to_stay_logged_in/) which says they're working on it.
I don't think this is an issue in Firefox but in Protonmail.

**Comment by stephanlachnit** [comment]
> I believe this happens because protonmail logs you out even if you change tabs / close, reopen tabs. I found [this 4 year old thread](https://www.reddit.com/r/ProtonMail/comments/5hwtzs/how_to_stay_logged_in/) which says they're working on it.
> I don't think this is an issue in Firefox but in Protonmail.

This doesn't really matter regarding functionality. I would love this feature even if I have to login again. The complicated part is to keep the info from the url after logging in.

**Comment by stephanlachnit** [comment]
Any update on this with the new web client?

**Comment by stephanlachnit** [comment]
@mmso is this fixed now?

**Comment by mmso** [comment]
@stephanlachnit this is being rolled out under the early access build

**Comment by stephanlachnit** [comment]
@mmso is there some kind of documentation already? I've already built a Firefox Addon (https://github.com/stephanlachnit/mailto_protonmail), it just requires adding the proper link where the mailto URI should be inserted.

**Comment by mmso** [comment]
Thanks for your effort, however a firefox addon won't be needed, we're natively [registering](https://github.com/ProtonMail/WebClients/blob/main/applications/mail/src/app/App.tsx#L26) a [protocol handler](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/registerProtocolHandler) which firefox supports

**Comment by stephanlachnit** [comment]
Ah true, I forgot they added that. Thanks.
