### ISSUE TITLE
The delete button deletes the first email when no email is checked.

### ISSUE THREAD

**Issue by AlexITC** [ProtonMail/WebClients#102]
**Describe the bug**
The delete button deletes the first email when no email is checked.

**To Reproduce**
1. Go to a folder having several emails.
2. Don't select anything and press the delete button.
3. The first email is deleted.

**Expected behavior**
Pressing the delete button when no email is selected should not delete any email.

**Comment by EpokK** [comment]
It deletes the first element of the list because the element is marked (so selected) with the left purple marker. It's a user experience choice.
