### ISSUE TITLE
API for custom web app

### ISSUE THREAD

**Issue by herman-rogers** [ProtonMail/WebClients#103]
**Is your feature request related to a problem? Please describe.**
Just a question really, wondering if there's an API I can use specifically to build my own custom web app for. Essentially I have some custom needs and would like to just build it.

**Describe the solution you'd like**
Just an API where I can access my account.

**Describe alternatives you've considered**
Adding my changes to the WebClient, although my changes are more for myself rather than for the wider community.

**Comment by dhoko** [comment]
Hey :wave: 

I don't understand when you run the webclient (via `$ npm start`) we attach it to this API `'https://mail.protonmail.com/api'`. It's our live API, so you're able to use your account. What is your issue ?

**Comment by herman-rogers** [comment]
Nah I just mean, can I create a third party app just for myself and still use the API? It sounds like I can from your comment.

**Comment by dhoko** [comment]
Yup :+1:

**Comment by bartbutler** [comment]
You might have trouble if you host it somewhere other than localhost or private IPs though, as the API will enforce CORS via the Origin header. You could get around this with an appropriate proxy though.

**Comment by herman-rogers** [comment]
I can just host it on an IP address - not really planning to host it on anything fancy. Worst case I’ll proxy it - cheers though.

**Comment by justinkalland** [comment]
Aloha @herman-rogers. A little late but I was also looking for an easy API library and couldn't find one, so I created it: [justinkalland/protonmail-api](https://github.com/justinkalland/protonmail-api)
