### ISSUE TITLE
Pagination buttons are way too far from the thread list.

### ISSUE THREAD

**Issue by JulienPalard** [ProtonMail/WebClients#104]
**Describe the bug**

When Protonmail switched from infinite-loading to paginated, the buttons poped *so far away* from the thread list I though it was a bug and it took me to [open an issue](https://github.com/ProtonMail/WebClient/issues/30) (taking a screenshot and so on) before finding them, see what I mean:

![](https://user-images.githubusercontent.com/28210502/29151133-328ce7b4-7d4d-11e7-9866-6de4a9767988.png)

I'm sure I'm not alone to have hard times to find the buttons, but I have no proof...

**Comment by eszterkv** [comment]
👋 hey Protonmail team, I'm happy to fix this :) I use the row view, but switching to column, pagination does seem far off to the right. I could do something like this (I'd leave the view switch to the right):

![updated_pagination_position](https://user-images.githubusercontent.com/16685596/45926783-e152ee00-bf1f-11e8-8ab1-7fc9ab796b2f.png)
