### ISSUE TITLE
Wrap WebClient in Electron and keep a locally cached copy of email

### ISSUE THREAD

**Issue by skewty** [ProtonMail/WebClients#105]
The subject line says it all.  Emails written while offline could be saved and sent later when an Internet connection was restored.  This would be great for customers who travel a lot.

**Comment by kontrollanten** [comment]
There's already an inofficial Electron wrapped client; https://github.com/protonmail-desktop/application But it sounds what you're looking for is ServiceWorker support

**Comment by skewty** [comment]
Yes [ServiceWorker](https://developers.google.com/web/fundamentals/primers/service-workers/) support would get part of the way there.  There is also registering to support things like "mailto:" links and being able to create a new email with file attachment from Files / Explorer / Finder.  That type of thing.

**Comment by ArcanisCz** [comment]
mailto support is subject of issue #101

**Comment by vladimiry** [comment]
@skewty, there is an unofficial desktop app I've been building https://github.com/vladimiry/email-securely-app/releases.

The app is already capable to keep an offline messages cache and reactively maintain the up-to-date state of the cache. You need to go with `beta` release to get the local cache feature, final v2 release is coming soon. So you can read the emails messages offline and also export all of the emails to EML files in a single mouse click.

Mailto stuff is supposed to be implemened within this issue https://github.com/vladimiry/email-securely-app/issues/62.

**Comment by skewty** [comment]
I will check it out for sure! Thank you for taking the time to reply to this thread.

Scott

Sent from ProtonMail mobile

-------- Original Message --------
