### ISSUE TITLE
Start app in docker container, permission denied

### ISSUE THREAD

**Issue by sjug** [ProtonMail/WebClients#11]
> # make start  
> ./bin/crun-node npm install --unsafe-perm --loglevel warn --no-bin-links
> + docker run -v /home/user/git/WebClient:/home/user/git/WebClient -v /tmp:/tmp -v /var/run/docker.sock:/var/run/docker.sock -e HOME=/home/user/git/WebClient -w /home/user/git/WebClient -e PATH=./node_modules/.bin/:./node_modules/grunt-cli/bin/:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin --rm -ti --sig-proxy=true node:5.11.1 npm install --unsafe-perm --loglevel warn --no-bin-links
> Error: EACCES: permission denied, scandir '/home/user/git/WebClient'
>     at Error (native)
> Error: EACCES: permission denied, open 'npm-debug.log.896050243'
>     at Error (native)
> 
> DOCKER_OPTS="-p 8080:8080" bin/crun-node npm start
> + docker run -v /home/user/git/WebClient:/home/user/git/WebClient -v /tmp:/tmp -v /var/run/docker.sock:/var/run/docker.sock -e HOME=/home/user/git/WebClient -w /home/user/git/WebClient -e PATH=./node_modules/.bin/:./node_modules/grunt-cli/bin/:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin -p 8080:8080 --rm -ti --sig-proxy=true node:5.11.1 npm start
> Error: EACCES: permission denied, scandir '/home/user/git/WebClient'
>     at Error (native)
> Error: EACCES: permission denied, open 'npm-debug.log.896050243'
>     at Error (native)

It's my user directory, so why would I be getting permission denied?

**Comment by vallode** [comment]
Just because something is in your user directory does not automatically mean you will have ownership over it. Look into the directory `/home/user/git` and `ls -l` to check roles/users on `WebClient`. 

It might also be that you have installed something the wrong way. You can always retrace your steps.

**Comment by ivanperez-keera** [comment]
What is crun-node?
