### ISSUE TITLE
Self hosting

### ISSUE THREAD

**Issue by zeroth** [ProtonMail/WebClients#12]
Hi,
I want to use ProtonMail web client as webmail client for my own SMTP and IMAP server (which are working fine and easily connects with all the stander mail clients) .
if you could point me to right config file or doc which explains how should I go about this will be really nice.

**Comment by Super-Baleine** [comment]
You are the second guy to ask this x)
Check this please : https://github.com/ProtonMail/WebClient/issues/5 x)
