### ISSUE TITLE
Autocrypt support

### ISSUE THREAD

**Issue by BuZZ-dEE** [ProtonMail/WebClients#120]
Hi there, is ProtonMail planning to follow the path of other mail clients and implement [Autocrypt](https://autocrypt.org/)? Seems like most major clients are planning on releasing support for it soon (K9, Thunderbird, Mailpile). There is also a email provider, [Posteo](https://posteo.de/en/blog/new-easy-email-encryption-with-autocrypt-and-openpgp-header), which supports Autocrypt. Would be nice if ProtonMail follows and stays compatible.

**Comment by Rafficer** [comment]
You may want to read [this](https://www.reddit.com/r/ProtonMail/comments/88gqiw/any_plans_to_support_autocrypt/dwrbb4b/) and [this](https://www.reddit.com/r/ProtonMail/comments/8dqk5n/protonmail_should_implement_autocrypt/dxpjpbb/).

**Comment by Erudition** [comment]
How about now, in 2019?
It would be nice to use Protonmail with something like [Delta.Chat](https://delta.chat/).

And even if the (unspecified) "security concerns" are still an issue today, is it really worse than plaintext emails?

**Comment by BuZZ-dEE** [comment]
@mmso why closed without comment?

**Comment by mmso** [comment]
This issue was closed as part of the migration to the new React codebase and mono-repository for Proton webapps. You are welcome to submit feature requests to https://protonmail.uservoice.com/forums/284483-protonmail and bug reports to https://protonmail.com/support/
