### ISSUE TITLE
pretty Easy privacy (pEp) support

### ISSUE THREAD

**Issue by BuZZ-dEE** [ProtonMail/WebClients#121]
https://www.pep.security/
https://en.wikipedia.org/wiki/Pretty_Easy_privacy
https://tools.ietf.org/html/draft-birk-pep-02

**Comment by BuZZ-dEE** [comment]
@mmso why closed without comment?

**Comment by mmso** [comment]
This issue was closed as part of the migration to the new React codebase and mono-repository for Proton webapps. You are welcome to submit feature requests to https://protonmail.uservoice.com/forums/284483-protonmail and bug reports to https://protonmail.com/support/
