### ISSUE TITLE
Use OpenPGP smart card to decrypt and sign emails

### ISSUE THREAD

**Issue by nagromc** [ProtonMail/WebClients#122]
**Is your feature request related to a problem? Please describe.**
My rule of thumb is to **never** reveal my private key to anyone, service, or device. Even on my own laptop, since my private key can leak through a malware that just copies it from my `~/.gnupg`. I use a smartcard to store my private key, generated from a laptop that never connects to the Internet.

Few days ago, I gave ProtonMail a try but could not find a way to use my existing OpenPGP private key stored on my smartcard.

**Describe the solution you'd like**
It would be great to use my smartcard from the web client (and Android client) to decrypt and sign my emails.

**Describe alternatives you've considered**
I could upload to ProtonMail my current signing and decrypting keys. But it would break my stated golden rule.

I could generate secondary signing and decrypting subkeys from my no-Internet laptop exclusively for ProtonMail:
- Master key (always offline)
    1. Main **signing** subkey
        - Already existing
        - Stored on my current smartcard
    2. Main **decrypting** subkey
        - Already existing
        - Stored on my current smartcard
    3. Secondary **signing** subkey
        - Needs to be created
        - Would be used exclusively for ProtonMail
        - Will be uploaded to ProtonMail web app
    4. Secondary **decrypting** subkey
        - Needs to be created
        - Would be used exclusively for ProtonMail
        - Will be uploaded to ProtonMail web app

The main drawback is that I would have multiple signing and decrypting subkeys and could be confusing for a GnuPG user. The GPG user could wonder what subkey he is supposed to use for encryption when sending me an email.

**Related issues**
Some more or less related features:
- https://github.com/mailvelope/mailvelope/issues/238
- https://github.com/openpgpjs/openpgpjs/issues/362
- https://github.com/openpgpjs/openpgpjs/issues/553

**Comment by nagromc** [comment]
Mailvelope has been released in [v3.0.0](https://github.com/mailvelope/mailvelope/releases/tag/v3.0.0) which includes native GnuPG integration:

> GnuPG integration: connect via native messaging with a GnuPG installation and use GnuPG as an alternative backend for all OpenPGP operations.

According to the official [release note](https://www.mailvelope.com/en/blog/mailvelope-3.0), this could make possible the use of hardware tokens:

> More about GnuPG integration and the possibilities of using **hardware tokens** will soon be available in a separate blog article.

**Comment by therealpxc** [comment]
I would really like to have this feature as well.

I use `pass` (https://www.passwordstore.org/) for password management, and I'd like to deal with as few PGP identities as possible for obvious reasons. But I'm not comfortable with the decryption keys for my password store living on any online computer.

As long as the private decryption keys for ProtonMail are stored online, I can't use those same keys for encrypting and decrypting other things, like my passwords. And that means that I'll have to do awkward things with GPG like maintain a separate identity or have inconsistent information on ProtonMail's keyservers versus others, because I want to be able to point people at at a keyserver and say 'encrypt for that identity', not point them directly to subkeys. :-\

**Comment by agireud** [comment]
It looks like `openpgpjs` added support last week: https://github.com/openpgpjs/openpgpjs/pull/865

**Comment by nagromc** [comment]
> 
> 
~> It looks like `openpgpjs` added support for this last week: [openpgpjs/openpgpjs#865](https://github.com/openpgpjs/openpgpjs/pull/865)~

~Well, not really. What I would like is to generate (or use, in my case) a subkey completely **offline**, then load it on my smartcard. What the [PR](https://github.com/openpgpjs/openpgpjs/pull/865) [fixes](https://github.com/openpgpjs/openpgpjs/issues/251) is the ability to extract the secret part of a subkey.~

~I don't want to extract the secret part of a subkey generated by ProtonMail since the service could be corrupted at generation time. I prefer to generate a subkey completely offline, then use it with my smartcard.~

Seems the person who commented deleted his comment.

**Comment by joshbuker** [comment]
+1 for supporting OpenPGP cards for email encryption/decryption.

**Comment by joshbuker** [comment]
@mmso if this isn't the correct place to indicate interest in smartcard support, where should we go instead?

**Comment by mmso** [comment]
@athix feature requests are welcome at https://protonmail.uservoice.com/forums/284483-protonmail

**Comment by joshbuker** [comment]
Ironically, it appears this is already the highest rated feedback on that forum: https://protonmail.uservoice.com/forums/284483-protonmail/suggestions/40434010-yubikey-ever-no-hello
