### ISSUE TITLE
Linting fails

### ISSUE THREAD

**Issue by vladimiry** [ProtonMail/WebClients#123]
Is linting not a part of the build/deploy pipeline?

**Describe the bug**
```
/WebClient/src/app/composer/controllers/composeMessage.js
  474:11  error  'wait' is assigned a value but never used  no-unused-vars

✖ 1 problem (1 error, 0 warnings)
```

**To Reproduce**
`npm run lint`

**Expected behavior**
1. No linting errors.
2. Project and build workflow is configured in the way that code with linting errors can't be merged to the upstream branch (husky + lint-staged, pull requests CI checks, etc).

CC @mmso

**Comment by dhoko** [comment]
Hey :wave: 
Weird, It is cf https://github.com/ProtonMail/WebClient/blob/public/tasks/deploy.js#L124 and we have circle.ci to validate a PR cf https://github.com/ProtonMail/WebClient/blob/public/circle.yml
:thinking: 

Maybe it's an issue during the chery pick, I will take a look.

**Comment by vladimiry** [comment]
By the way it now ends up with even more errors:
```
/webclient/src/app/app.js
  22:20  error  Unable to resolve path to module './config'  import/no-unresolved
/webclient/src/app/attachments/services/attachmentApi.js
  1:20  error  Unable to resolve path to module '../../config'  import/no-unresolved
/webclient/src/app/bugReport/services/bugReportApi.js
  12:20  error  Unable to resolve path to module '../../config'  import/no-unresolved
/webclient/src/app/commons/directives/appCopyright.js
  1:20  error  Unable to resolve path to module '../../config'  import/no-unresolved
/webclient/src/app/commons/models/eo.js
  3:20  error  Unable to resolve path to module '../../config'  import/no-unresolved
/webclient/src/app/commons/services/i18nLoader.js
  3:20  error  Unable to resolve path to module '../../config'  import/no-unresolved
/webclient/src/app/commons/services/url.js
  1:20  error  Unable to resolve path to module '../../config'  import/no-unresolved
/webclient/src/app/composer/controllers/composeMessage.js
  474:11  error  'wait' is assigned a value but never used  no-unused-vars
/webclient/src/app/core/factories/releaseNotesModal.js
  1:20  error  Unable to resolve path to module '../../config'  import/no-unresolved
/webclient/src/app/ui/directives/appVersion.js
  1:20  error  Unable to resolve path to module '../../config'  import/no-unresolved
✖ 10 problems (10 errors, 0 warnings)
```

**Comment by vladimiry** [comment]
Apparently, since [this](https://github.com/ProtonMail/WebClient/commit/0c70d6a21656257a263af7b9f3e6c9438b3ebe98) commit the app depends on some `/webclient/src/app/config` file which has not been committed.

@dhoko / @mmso is there a way to build the project locally from the repository HEAD? So I could run it on localhost?

**Comment by dhoko** [comment]
> By the way it now ends up with even more errors:

Did you try to run the project via `$ npm start` ? Because npm start will generate this file for you as it's not static.

**Comment by vladimiry** [comment]
I did and it starts, but I need to get a completely static bundle, so I could run it with any server as a static thing. That's why I'm asking about building, not starting.

**Comment by dhoko** [comment]
ok, then you can do 
1. `$ npm run config`
2. `$ npm run dist`

It will create the config, then you will be able to build the app.

**Comment by vladimiry** [comment]
@dhoko I'm able to build a static bundle that way, thanks. The original linting issue still remains though.

**Comment by dhoko** [comment]
Not anymore ;) cf this commit  https://github.com/ProtonMail/WebClient/commit/9b224b2ac01f9d4258979674d9151bc42677a8b9

**Comment by vladimiry** [comment]
I confirm linting doesn't fail anymore, but only having executed `npm run config` before. That's not what I would expect, but it works for me.

> 2. Project and build workflow is configured in the way that code with linting errors can't be merged to the upstream branch (husky + lint-staged, pull requests CI checks, etc).

The second point is up to you.

Closing the issue, thanks.
