### ISSUE TITLE
`Sent by you with end-to-end encryption` but not end-to-end encrypted

### ISSUE THREAD

**Issue by nagromc** [ProtonMail/WebClients#127]
**Describe the bug**
On an e-mail sent to a non-ProtonMail address, the padlock shows the following message:

> Sent by you with end-to-end encryption

However, the [documentation](https://protonmail.com/support/knowledge-base/what-is-encrypted/) states the following:

> Emails from ProtonMail users to non-ProtonMail users
>
> - End-to-end encrypted if the “Encrypt for Outside” option is selected. Learn more here.
> - Otherwise **encrypted with TLS** if the non-ProtonMail mail server supports it (most providers such as Gmail, Yahoo, Hotmail, etc, support TLS). Note, since these messages are encrypted, but **not end-to-end encrypted**, this means Gmail, Yahoo, Hotmail, etc, will be able to read these messages and hand them over. This is not possible if “Encrypt for Outside” is set and ProtonMail end-to-end encryption is enabled.

Please note the _Encryption_ button (or _Encrypt for Outside option_ in the documentation) has not been checked.

**To Reproduce**
1. In ProtonMail, click _Compose_ button
2. In the _Recipients_ field, enter a non-ProtonMail address (a Gmail address for instance)
3. Enter _foo_ in the _Subject_ field, and _bar_ in the body
4. Send the e-mail
5. In ProtonMail, click _Sent_, and display the e-mail just sent
6. See a purple padlock with the message _Sent by you with end-to-end encryption_ 
    ![image](https://user-images.githubusercontent.com/752443/49804064-e884dd80-fd51-11e8-8812-0e3549dee2f6.png)
7. In the recipient mailbox (Gmail in our example), see the e-mail in cleartext (subject and body)
    ![image](https://user-images.githubusercontent.com/752443/49804242-5cbf8100-fd52-11e8-9a22-e5c4cf5ea62d.png)

**Expected behavior**
I was expecting either:
- In ProtonMail: see a padlock with a message like _Sent in cleartext, using a secure channel_
- In Gmail: an OpenPGP encrypted e-mail (with `-----BEGIN PGP MESSAGE-----` & `-----END PGP MESSAGE-----` tags)

**Screenshots**
See in _To Reproduce_ section

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox 63.0.3
 - Version: ProtonMail v3.15.5
 - URL: beta.protonmail.com

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by nirvinm** [comment]
Yes. I can reproduce this issue on both Webmail and Android.

When replying to non-ProtonMail users, message is being shown as end-to-end encrypted on Sent Items. The padlock icon is misinforming users and should be revisited.

**Comment by bartbutler** [comment]
This bug is now fixed for new sent messages. We will retroactively fix the old sent messages at some point as well. The lock mouseover text now only says end-to-end encryption if all recipients were sent encrypted messages. Sorry for the inconvenience!

Please note that the encryption and signing status for recipients individually on recent sent messages is available if you click 'Show details' in the message view on the web app, and this information has always been accurate.
