### ISSUE TITLE
[sync Webclient] Production deployed with build compiled from some hidden place but not from this repository

### ISSUE THREAD

**Issue by vladimiry** [ProtonMail/WebClients#129]
Deployed production version: 3.15.7
Repository version: 3.15.5

So the project is open-source, but production deployed from some hidden repository.

**Expected behavior**

- Deployed to production build always matches the code in this repository.
- In along with deploying, CI job creates the respective tag or release in this repository. So it's clear which exact commit is deployed.
- An option to verify that deployed to production version has been built from the code in this repository. Ideally linked to this repository CI server does all the job of building and deploying, so anyone concerned could review the CI logs.

**To Reproduce**

![deployed-from-private-repository](https://user-images.githubusercontent.com/1560781/50319401-434bd100-04d8-11e9-944f-b393a9d76983.png)

**Comment by ArcanisCz** [comment]
In open source project, especially security related ones, builds should really be reproducible. Not only matching versions, but file (and libraries) hashes too.

**Comment by dhoko** [comment]
100% agree, it's a wip :) 
We must provide checksums, way to install the same config, dist sources etc.

**Comment by ArcanisCz** [comment]
awesome :)

**Comment by vladimiry** [comment]
By the way, it happens again. Production got deployed with possibly shady build again. Shady means deployed with build taken from some hidden place, but not from this repository.

Deployed production version: 3.15.14
Repository version: 3.15.13

![again](https://user-images.githubusercontent.com/1560781/51679965-701c6800-1ff1-11e9-9c8f-938e716d9867.png)

**Comment by dhoko** [comment]
Oups :/ It's fixed now

**Comment by vladimiry** [comment]
Here we are again:

![proton](https://user-images.githubusercontent.com/1560781/55089395-63ce8d00-50be-11e9-8b57-5af4e7b20f00.png)

**Comment by dhoko** [comment]
My bad, I forgot to sync. :/

**Comment by vladimiry** [comment]
Thanks.

It's unrelated, but https://beta.protonmail.com/ is not loading with integrity checking errors in dev console.

**Comment by dhoko** [comment]
@vladimiry there was an issue with the build on beta :/ cf https://github.com/ProtonMail/WebClient/issues/148

**Comment by vladimiry** [comment]
git: 3.15.27
live: 3.15.29
![live-vs-git-versions](https://user-images.githubusercontent.com/1560781/56880079-097d6f00-6a64-11e9-995c-74aa1aae9c4a.png)

**Comment by dhoko** [comment]
voilà ;)

**Comment by vladimiry** [comment]
Friendly reminding (need to update [ElectronMail](https://github.com/vladimiry/ElectronMail) before new release).
![version](https://user-images.githubusercontent.com/1560781/58186107-ea69aa00-7cbc-11e9-8743-3c8a705f4a61.png)

**Comment by dhoko** [comment]
Voilà, sorry we needed to debug something :grin:

**Comment by vladimiry** [comment]
3.16.3 has not been published here.

**Comment by vladimiry** [comment]
ping

**Comment by vladimiry** [comment]
ping (7 days source code publishing lag)

**Comment by vladimiry** [comment]
ping (8 days source code publishing lag)

**Comment by EpokK** [comment]
@vladimiry done.

**Comment by vladimiry** [comment]
Thanks. Any progress in automating the code publishing process or even better deploying from the public repo? As a temporary supporting solution, I guess an automated notification triggered by new release event could be set up. This notification would inform the concerned parties that the code needs to be published here.

**Comment by EpokK** [comment]
We are currently refactoring Proton web-apps in React for version 4, all repo are currently public and available [there](https://github.com/ProtonMail). Our attention is more on the new version than the old Angular repo. For next release on that one, we will add attention to sync repos properly.

**Comment by vladimiry** [comment]
beta 11 is not shared yet but deployed.

Besides I guess `proton-mail-settings + proton-contacts  + proton-calendar ` should be published too as they supposed to use [updated](https://github.com/ProtonMail/proton-shared/blob/master/lib/createSecureSessionStorage.js) `proton-shared` project.

Please don't miss syncing package lock files.

**Comment by vladimiry** [comment]
v4.0.0-beta13 is live now but not published here yet. Please also publish all the related projects if they have been updated, and lock files too.

**Comment by vladimiry** [comment]
@dhoko do I get it right that the DKIM-related issue detected in beta 16 was somewhere in backend side and that's why I see no changes in client repositories after beta 16 got re-deployed today? Asking since I'm trying to realize if I need to rebuild the WebClient/proton-mail-settings/proton-contacts/proton-calendar event though there was no code update nor in the lock files.

**Comment by dhoko** [comment]
@vladimiry  Yep, we switched back the beta to go back to the 15. The fix is now available on the API side, that's why we deployed the beta 16 again (_it's the same bundle we built the first time_).

No need to rebuild the beta 16, if you did it a few days ago. :+1:
