### ISSUE TITLE
Question : PKP

### ISSUE THREAD

**Issue by Super-Baleine** [ProtonMail/WebClients#13]
Hey :whale:,
HPKP is disabled, will you enable it ?

![capture du 2016-08-26 23 06 01](https://cloud.githubusercontent.com/assets/13090164/18020486/d7ab99da-6be1-11e6-9f0e-1b76e4d90fb1.png)

Source : SSLlabs

**Comment by bartbutler** [comment]
I think this is the wrong forum for this question, as it doesn't concern the Web Client project itself. That said, what domain are you running this against? I checked protonmail.com and mail.protonmail.com with SSL Labs and we have Public Key Pinning Report-Only running there.

**Comment by Super-Baleine** [comment]
Where is the forum to ask this kind of question ?
Oh, i didn't see it... (screenshot), bizarre... But okay :)

**Comment by Super-Baleine** [comment]
Oh, i forgot to answer : i used protonmail.ch

You should look at the new tool of Mozilla : https://observatory.mozilla.org/analyze.html?host=mail.protonmail.ch

It's very powerful.

**Comment by bartbutler** [comment]
It might not be on protonmail.ch...if so we'll fix it. This kind of question should be sent to security@protonmail.ch

**Comment by Super-Baleine** [comment]
Hmm, okay, even if it's a futile question ?

**Comment by bartbutler** [comment]
It's not futile. HPKP reporting is indeed off on protonmail.ch and we should fix it, and it is a minor security issue. For general queries about ProtonMail, use contact@protonmail.ch. Github issues on this repo should be for Web Client issues, not server configuration.

**Comment by Super-Baleine** [comment]
Okay, thanks ! x)
