### ISSUE TITLE
A concern about npm and security

### ISSUE THREAD

**Issue by lifepillar** [ProtonMail/WebClients#134]
Your web client downloads hundreds of npm packages. As npm does not have a track as the most secure and malware-free ecosystem on the planet, I am wondering… are you taking any measures to verify third-party code and make your app trusted? (Sorry if this question has been asked already, but I couldn't find any information about that).

**Comment by kontrollanten** [comment]
It may be a great idea to run [snyk](https://snyk.io) tests in the CI environment and add a snyk badge to be transparent about the status?

**Comment by lifepillar** [comment]
That would certainly inspire more confidence. I would also consider reducing the number of dependencies as a medium/long term goal…
