### ISSUE TITLE
RFE - Snooze emails & reminders until later

### ISSUE THREAD

**Issue by EmilienM** [ProtonMail/WebClients#138]
**Is your feature request related to a problem? Please describe.**
Snooze emails and reminders to temporarily remove them from your inbox until you need them.

**Describe the solution you'd like**
My email or reminder will come back to the top of my inbox when I want it to, whether that's tomorrow, or next week. I can always see your snoozed items under Snoozed in the Menu.

**Describe alternatives you've considered**

**Additional context**
Feature from Gmail:
https://support.google.com/inbox/answer/6067583?co=GENIE.Platform%3DDesktop&hl=en

**Comment by georgespatton** [comment]
This is on Android, can we have it on the web client too?

**Comment by EmilienM** [comment]
> This is on Android, can we have it on the web client too?

where do you have seen it on Android? I don't see it.

**Comment by georgespatton** [comment]
> > This is on Android, can we have it on the web client too?
> 
> where do you have seen it on Android? I don't see it.

Looks like it might have been there at some point per this thread:  https://www.reddit.com/r/ProtonMail/comments/e53jdl/snooze_mail_request/  but I looked at the current version of Android and I do not see it as a feature anymore.

**Comment by tyleroconnell** [comment]
@mmso I see this was closed but I don't yet see the functionality in beta, any timeline for when this might be available?

**Comment by mmso** [comment]
This issue was closed as part of the migration to the new React codebase and mono-repository for Proton webapps. You are welcome to submit feature requests to https://protonmail.uservoice.com/forums/284483-protonmail

**Comment by EmilienM** [comment]
This was implemented and documented here: https://proton.me/support/schedule-email-send
Thanks ProtonMail!
