### ISSUE TITLE
Modern font stack

### ISSUE THREAD

**Issue by nicolas-t** [ProtonMail/WebClients#139]
**Is your feature request related to a problem? Please describe.**
The current font stack : 
`font-family: Arial, "Helvetica Neue", Helvetica, sans-serif;` 
features old fonts with few font-weights.
While still relying on native/system fonts we could achieve way better results using modern fonts.

**Describe the solution you'd like**
We could use a more modern font stack, using system fonts.

For example the font stack used by github : 
`font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol";` 

Or bootstrap : 
https://getbootstrap.com/docs/4.0/content/reboot/#native-font-stack

**I can make a pull request if you're interested.**

Thanks,

You can read more about it here : 
https://bitsofco.de/the-new-system-font-stack/

**Comment by nico3333fr** [comment]
Thank you, that is great suggestion. 👍 

We will consider (or implement) in our next major version. See this blog post for the official roadmap: https://protonmail.com/blog/2018-recap-future-roadmap/ 

Anyway, you may use it in a custom theme ;) (as far as we can see in our tests, this works like a charm)
