### ISSUE TITLE
SIGN UP FAILED

### ISSUE THREAD

**Issue by KrzysztofMadejski** [ProtonMail/WebClients#14]
![proton-signup](https://cloud.githubusercontent.com/assets/849975/18543492/3974e6e4-7b41-11e6-9ba8-348156966544.PNG)

Issues:
- [ ] signup has failed - no idea why
- [ ] link to the common problems (click here) is improperly contructed: https://mail.protonmail.com/%E2%80%9Chttps://protonmail.com/support/knowledge-base/common-sign-up-problems-and-solutions/%E2%80%9C (relative mixed with absolute + a quote at the end)

**Comment by emersion** [comment]
>  signup has failed - no idea why

Please contact customer support.

> link to the common problems (click here) is improperly contructed

Fixed in latest release.
