### ISSUE TITLE
Renaming labels breaks filters

### ISSUE THREAD

**Issue by dmtucker** [ProtonMail/WebClients#140]
**Describe the bug**
Renaming a Label causes Filters to stop applying it.

**To Reproduce**
1. Create a Label, A.
2. Create a Filter that applies Label A.
3. Rename the Label to B.
4. See that the Filter no longer applies any Labels.

**Expected behavior**
Filters are unaffected by changes to Labels.

**Desktop (please complete the following information):**
 - OS: Mac OS 10.13.6
 - Browser: Safari 12.0.3
 - URL: https://mail.protonmail.com/

**Comment by bartbutler** [comment]
Going to mark this as WONTFIX--reparsing potentially large numbers of filters every time someone makes a label name change is not feasible, and the filters use Sieve as the underlying filtering language which uses label names, so it's not possible to use an invariant label identifier there.

**Comment by florianehmke** [comment]
Honestly this seems like something that should just work.
I just renamed several labels and discovered _all_ filters are now broken.
I would suggest to either fix this or else show at least a very prominent warning so people don't discover this the hard way when it's too late.
