### ISSUE TITLE
Slahes in e-mail addresses cause issues with contact features

### ISSUE THREAD

**Issue by emersion** [ProtonMail/WebClients#145]
**Describe the bug**
Some special characters like `/` are stripped from the contact view's addresses. Additionally, when sending an e-mail to this address, the receiver's address is not matched with the contact (see below).

**To Reproduce**
1. Add a contact with a slash in it, e.g. `~emersion/mrsh-dev@lists.sr.ht`
2. Receive an e-mail from this contact
3. Go to contacts list, slashes are stripped
4. Go to e-mail received from or sent to this contact, it's as is the contact didn't exist (popover shows "Add to contacts" instead of "See contact details")
5. When composing an e-mail to this address, contact settings like PGP signature/encryption aren't applied

All of this happens with v3.15.19.

**Expected behavior**
Slashes are valid characters in e-mail addresses. See https://stackoverflow.com/questions/2049502/what-characters-are-allowed-in-an-email-address

**Screenshots**

![](https://sr.ht/e7tD.png)

![](https://sr.ht/GAdw.png)

**Comment by XeroOl** [comment]
I'm still having issues with slash `/` characters in email addresses. It works when viewed from the contact page, but the slashes are still stripped when attempting to send the email.

`/` present in contact page, as expected
![image the slash is present](https://github.com/ProtonMail/WebClients/assets/6820998/0b201a85-4df9-4ad8-b5e2-1c8a044b3ef8)
`/` missing, causing the message to be sent to the wrong address
![image where the slash is missing](https://github.com/ProtonMail/WebClients/assets/6820998/6473cc87-382e-452f-aa87-b67bdebe5a73)

This is in Proton Mail5.0.35.9 β
