### ISSUE TITLE
"transformEscape" fails with "RangeError: Maximum call stack size exceeded"

### ISSUE THREAD

**Issue by vladimiry** [ProtonMail/WebClients#146]
It fails on `input.replace` call: https://github.com/ProtonMail/WebClient/blob/65c3bdd8a31d8b3280ab3f478ed17d33e5e3a64c/src/app/message/helpers/transformEscape.js#L126

The real world case is being tracked here https://github.com/vladimiry/email-securely-app/issues/112#issuecomment-469959323. I don't have access to the original email's content but the issue can be reproduced by execute something like this in browser's dev console:
```javascript
// ~ 5,88 MB input string
var string = [
    '<script poster=""gggggggggggggggggggggggggggggggggggg">',
    ...Array(168000).fill('<script poster=\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\>')
].join('');

//  see https://github.com/ProtonMail/WebClient/blob/65c3bdd8a31d8b3280ab3f478ed17d33e5e3a64c/src/app/message/helpers/transformEscape.js#L68
var REGEXP_IS_BREAK = /([^-])(svg|xlink:href|srcset=|src=|background=|poster=)(?=(([^"><\\]|\\[^><])|("(\\.|[^"\\])*"))*>)/gi;

console.log(
    string
        .replace(REGEXP_IS_BREAK, '$1proton-$2')
        .length
);
```

Chrome:
![rangeerror](https://user-images.githubusercontent.com/1560781/53881106-dc907b00-4023-11e9-9d44-03f14e36d3f5.png)

Firefox will raise another error type but this is the same case:
![internalerror](https://user-images.githubusercontent.com/1560781/53881102-d9958a80-4023-11e9-8229-bc87b629ceb4.png)

**Comment by dhoko** [comment]
A fix is available with the new version v3.16.1. The regexp changed, now we escape most of the things via DomPurify
