### ISSUE TITLE
Resource integrity issue on beta.protonmail on 3.15.22

### ISSUE THREAD

**Issue by Pegase745** [ProtonMail/WebClients#148]
**Describe the bug**
The upgrade to `3.15.22` works on `mail.protonmail.com` but not `beta.protonmail.com`.

**To Reproduce**
1. Go to 'beta.protonmail.com'
2. See error

**Screenshots**
![2019-03-27-170007_1918x1058_scrot](https://user-images.githubusercontent.com/1678801/55091961-03395300-50b2-11e9-9332-31d765d6b8a9.png)

**Comment by EpokK** [comment]
Thanks for your report. If you hard refresh your tab on `beta.protonmail.com` it should be fixed right now.
