### ISSUE TITLE
Add a setting to change date format

### ISSUE THREAD

**Issue by etanot** [ProtonMail/WebClients#149]
**Is your feature request related to a problem? Please describe.**
Add a setting to change date format shown in upper right-most corner in the mail.

**Describe the solution you'd like**
 I would mostly preferred DD/MM/YYYY format but It seems like date format depends on the browser which is fine with [Chromium browser](https://user-images.githubusercontent.com/28824347/55269724-929b5d80-528e-11e9-8edb-65d28faa9686.jpg). But, when I open my email account using [Brave](https://brave.com) date shown in [MM/DD/YYYY](https://user-images.githubusercontent.com/28824347/55269717-81eae780-528e-11e9-8066-cbf2faee474a.jpg) format which I don't like.

**Additional context**
Date format 1 : MM/DD/YYYY ( snapshot from Brave browser)
![Date format 1](https://user-images.githubusercontent.com/28824347/55269717-81eae780-528e-11e9-8066-cbf2faee474a.jpg)

Date format 2 : DD/MM/YYYY ( sanpshot from Chromium browser)
![Date format 2](https://user-images.githubusercontent.com/28824347/55269724-929b5d80-528e-11e9-8edb-65d28faa9686.jpg)

**Comment by herman-rogers** [comment]
Are you sure your date settings in brave aren't set to US/American date time?

**Comment by etanot** [comment]
@herman-rogers  My system date & time is in US/American format. In both Chromium and Brave browser(which is chromium based but both show date in different format) I don't find any setting related to change date & time. Can I change my date & time setting of browser without any help from extension? If yes, How? Is date format depends on OS date & time format?
