### ISSUE TITLE
Kabyle language: Native name

### ISSUE THREAD

**Issue by MohammedBelkacem** [ProtonMail/WebClients#152]
**Describe the bug**

**To Reproduce**
1. Go to '...'  https://protonmail.com/
2. Click on '....'  Language list
3. Scroll down to '....' Kab
4. See error : it shows Tazwawt ruther than Taqbaylit

**Expected behavior**
The native language name of Kabyle is Taqbaylit.

![2019-05-07 19_30_13-Secure email_ ProtonMail is free encrypted email](https://user-images.githubusercontent.com/7033740/57323938-1276dc00-7107-11e9-86a8-f01d1c7ee227.jpg)

**Comment by nico3333fr** [comment]
Thanks a lot @mozillakab for this info, the fix went live a few minutes ago 🎉 

![image](https://user-images.githubusercontent.com/2578321/57525765-e25c5280-732b-11e9-971a-5b48ebc237a6.png)

Thanks again 👍

**Comment by MohammedBelkacem** [comment]
@dhoko 

Thanks, verified. It's ok
