### ISSUE TITLE
Custom Domain Address / User

### ISSUE THREAD

**Issue by lionelvlobo** [ProtonMail/WebClients#153]
Custom Domain : 
Address can be disabled, but cannot be deleted. 

**Actual Behavior**

- User created custom domain i.e protoncustomdomain.com. 
- User had trouble understanding adding address / adding user. 
![Screen Shot 2019-05-09 at 4 56 35 PM](https://user-images.githubusercontent.com/50457654/57471588-c7d29c80-728b-11e9-9401-d674131eed05.png)

- User added new address i.e bruce.wayne@protoncustomdomain.com, thomas.wayne@protoncustomdomain.com, martha.wayne@protoncustomdomain.com. 
- Furthermore the user started to migrate existing emails from a **Gmail demo account** over to one of the ProtonMail user accounts the created. Using the import/export guide completed the process. Moreover, using the ProtonMail import/export tool, imported emails to bruce.wayne@protoncustomdomain.com. 
- Import complete- Under Folders/Labels. 
- User later realized that "addresses" were added instead of intended "users". 
- User made corrections by deleting the addresses, however bruce.wayne@protoncustomdomain.com cannot be deleted with pop up message "Address cannot be deleted while messages associated with this address exist". 
![Screen Shot 2019-05-09 at 4 47 59 PM](https://user-images.githubusercontent.com/50457654/57471956-a7efa880-728c-11e9-9053-7e4adff2f171.png)

- User cleared all mails pertaining to bruce.wayne@protoncustomdomain.com, however pop message keeps appearing failing to delete the address. 
![Screen Shot 2019-05-09 at 6 58 53 PM](https://user-images.githubusercontent.com/50457654/57472150-13397a80-728d-11e9-8239-357d4af20beb.png)
![Screen Shot 2019-05-09 at 6 57 47 PM](https://user-images.githubusercontent.com/50457654/57472644-3d3f6c80-728e-11e9-8476-f3468f3ebc23.png)

**Expected behavior**
Address has to be deleted on command.  

**Desktop :**
 - OS: Mac OS
 - Browser [Chrome, Safari]
 - Resolution [e.g. 1440x900]
 - URL [e.g. mail.protonmail.com]

**Comment by valentinbonneaud** [comment]
Did the user empty the trash? I cannot reproduce on live with my custom domain.

**Comment by lionelvlobo** [comment]
Hey Valentin,

Trash has been cleared. Alex and I made sure that no emails pertaining to the Bruce Wayne address exists.

LvL
