### ISSUE TITLE
Make start fails due to missing crun-node

### ISSUE THREAD

**Issue by ivanperez-keera** [ProtonMail/WebClients#155]
**Describe the bug**
The command to create the docker image, `make start`, fails due to `./bin/crun-node` being missing.

**To Reproduce**
1. Go to top-level dir in the repo.
2. Run `make start`

**Expected behavior**
I would expect the app to create a docker image and bind it?

Instead, I get:
```bash
$ make start
./bin/crun-node npm install --unsafe-perm --loglevel warn --no-bin-links
make: ./bin/crun-node: Command not found
Makefile:8: recipe for target 'npm-install' failed
```

**Comment by dhoko** [comment]
The Makefile is old we don't use it (_cf [the Readme](https://github.com/ProtonMail/WebClient#basic-installation)_). We should remove it, it's based on a directory bin inside WebClient cf https://github.com/ProtonMail/WebClient/tree/966abf48e45590b6ab930374abe094e8b40849c3.
We removed it but we forgot to remove the makefile.

Today we use npm scripts.
