### ISSUE TITLE
still Jquery in dependencies! 

### ISSUE THREAD

**Issue by ghost** [ProtonMail/WebClients#156]
drop jquery. You don't need Jquery anymore.

**Comment by dhoko** [comment]
We need jQuery for some plugins such as timepicker etc. 
> You don't need Jquery anymore.

It doesn't mean you have to remove it too ;) Don't forget, we are also using AngularJS 1 :grin: 
Spoiler alert: it's going to be out of the app cf: https://github.com/ProtonMail/react-components

**Comment by ghost** [comment]
Ok i understand. But please use modern JavaScript.
