### ISSUE TITLE
Not able to login on local setup using production credentials

### ISSUE THREAD

**Issue by akanshgulati** [ProtonMail/WebClients#161]
**Describe the bug**
I am trying to setup WebClient and installed it successfully. On login screen on local machine, running at port 8080, I am getting these two errors while using same credentials as production one, 
`Invalid access token`
`Invalid Input`

**To Reproduce**
1. node =  12.11.1
2. npm = 6.11.3
3. url : `http://localhost:8080/login`

**Expected behavior**
Not able to work on an issue due to this. Ideally, it should log me in and let me reproduce other issue. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version 77.0.3865.90
 - Resolution : 1440x900
 - URL http://localhost:8080/login

**Comment by dhoko** [comment]
:wave: 

Hum for me it works :/
I did:
1. `$ git clone --depth 1 git@github.com:ProtonMail/WebClient.git`
2. `$ npm ci`
3. `$ npm start` 

And I was able to login. What do you see post npm start ?
ex: 
![Screenshot from 2019-10-14 09-50-26](https://user-images.githubusercontent.com/713283/66736010-5913f380-ee68-11e9-8652-98997482d50a.png)
 
Edit: Maybe it's an issue with a plugin -> µMatrix ?

**Comment by akanshgulati** [comment]
@dhoko  Can you please share the node version too. Will try install packages again as with `npm ci` too it didn't work. I am getting same response as above.

**Comment by dhoko** [comment]
```sh
$ nvm install v12
Downloading and installing node v12.12.0...
Downloading https://nodejs.org/dist/v12.12.0/node-v12.12.0-linux-x64.tar.xz...
######################################################################### 100,0%
Computing checksum with sha256sum
Checksums matched!
Now using node v12.12.0 (npm v6.11.3)
``` 

I wasn't testing with node 12, but it doesn't change anything for me :) 

If it's still not ok, what do you see inside the console ?
