### ISSUE TITLE
Browser extension

### ISSUE THREAD

**Issue by erotavlasme** [ProtonMail/WebClients#163]
Hi,
please in order to enhance security and speed of protonmail web app it would be good to have a browser extension (firefox and chromium based browser). This will allow to run the app locally and avoid to download javascript, HTML and CSS from servers via HTTPS every time. Moreover, the browser extension updates can be protected by cryptography.
There is already an [open source extension](https://github.com/gitladen7/protonmail-webextension), you could contact the author.
Best Regards.

**Comment by vladimiry** [comment]
> This will allow to run the app locally and avoid to download javascript, HTML and CSS from wire servers via HTTPS every time.

The extension you referenced loads the web client from the internet. Ie the web client is not prepackaged with the extension as a static resource.

**Comment by erotavlasme** [comment]
> > This will allow to run the app locally and avoid to download javascript, HTML and CSS from wire servers via HTTPS every time.
> 
> The extension you referenced loads the web client from the internet. Ie the web client is not prepackaged with the extension as a static resource.

It is true. Indeed, I wrote that protonMail could start from this open source extension not that it is ready.

**Comment by gitladen7** [comment]
Hello,

That would be great! I can transfer the ownership of the Chrome, Opera and Firefox extension stores if needed.

Regards.

**Comment by erotavlasme** [comment]
Hi,
since now all the [protonMail apps](https://protonmail.com/blog/android-open-source/) are open source and audited, protonMail should consider to develop a browser extension in order to increase the security.
