### ISSUE TITLE
Option - Display Senders Gravatar Images

### ISSUE THREAD

**Issue by coliff** [ProtonMail/WebClients#167]
**Describe the solution you'd like**

The senders initials in a circle in message list view doesn't make it easily to quickly scan to see the sender. If Protonmail could first check if a user has a Gravatar that would be very helpful. Gravatar is very popular and used by many sites and services including WordPress, GitHub, Slack, Stackoverflow, and some third-party email clients too.
REF: https://gravatar.com/

**Comment by Rafficer** [comment]
I can already feel the backlash this feature would bring because it automatically establishes connections to an American company.

**Comment by coliff** [comment]
> I can already feel the backlash this feature would bring because it automatically establishes connections to an American company.

If it was an option at least (disabled by default even)
