### ISSUE TITLE
Share "proton-translations" project

### ISSUE THREAD

**Issue by vladimiry** [ProtonMail/WebClients#176]
Also what do I fill in the `I18N_DEPENDENCY_REPO` and `I18N_DEPENDENCY_BRANCH_V4` env variables? Needed for running `proton-i18n post-install` command.

https://github.com/ProtonMail/proton-i18n/blob/a21bb5a60f3b1e52e52d6ea39cb2ca171ee75c60/config.js#L62-L65

**Comment by dhoko** [comment]
hum no need to add these variables, I'm going to add a fallback mode which is going to download the same version as the one deployed live.

cf https://github.com/ProtonMail/proton-i18n/pull/14 

The env is about the git clone url of the translations repo https://github.com/ProtonMail/proton-translations and the branch/app.

But it's really usefull only for us as if you use it as it is now you might load translations not matching what's live.

The new version of proton-i18n will load the same locales we deployed, so for you it will be easier to use as you won't need to configure anything :)

**Comment by dhoko** [comment]
The repository is here https://github.com/ProtonMail/proton-translations with all branches.
No need add a custom config inside your env (_you will get a warning but it's not an issue_) as proton-i18n _version 2.0.6_ will try to download the translations we have live for this app.

cf
![Screenshot from 2020-02-27 18-59-13](https://user-images.githubusercontent.com/713283/75528076-61358f80-5a13-11ea-9f8c-11a15b4eb1e1.png)

**Comment by vladimiry** [comment]
Thanks. Going to confirm issue resolving after trying the changes in ElectronMail.

**Comment by dhoko** [comment]
@vladimiry new beta 10 with the new dep is available

**Comment by vladimiry** [comment]
@dhoko I tried the updated webclient project and `npx proton-i18n post-install` command successfully created the `proton-translations` folder with json files in it. But I have to run `npx proton-i18n post-install` before building all the projects, so the `LOCALES` value in `./src/app/config.ts` gets filled from the `proton-translations` folder. So can you update the lock files of `proton-mail-settings  / proton-contacts / proton-calendar` projects since they need to get updated `proton-i18n` module?

Right now if I build for example `proton-mail-settings` project, I get the empty drop-down in the language selection section.

**Comment by vladimiry** [comment]
And by the way can the `npx proton-i18n post-install` be incorporated by `proton-pack` project, so I just run `npm run build`-like command and get the project compiled with languages included?

**Comment by dhoko** [comment]
> But I have to run npx proton-i18n post-install before building all the projects,

Hum it should be done via the postinstall hook, maybe an issue with unsafe-perm on your side?
cf:
``` 
 npm WARN lifecycle proton-mail-settings@1.0.0~postinstall: cannot run in wd proton-mail-settings@1.0.0 proton-i18n post-install (wd=/builds/web/mail/proton-mail-settings)
```

**Comment by vladimiry** [comment]
proton-mail-settings 9bc0c5023aa05b74ebac7e337e2c042c7019bed1 comes with broken lock file:

```
npm ci 

electron-mail/output/git/proton-mail-settings/9bc0c5023aa05b74ebac7e337e2c042c7019bed1/app.protonmail.ch"

npm ERR! cipm can only install packages when your package.json and package-lock.json or npm-shrinkwrap.json are in sync. Please update your lock file with `npm install` before continuing.
npm ERR! 
npm ERR! 
npm ERR! Missing: proton-bundler@github:ProtonMail/proton-bundler#semver:^2.0.0
```

**Comment by vladimiry** [comment]
> Hum it should be done via the postinstall hook

Yes it does and `LOCALES` var defined in `./src/app/config.ts` is filled. I had to install `proton-mail-settings` deps using `npm install` instead of `npm ci` since lock file is in out of sync state:

```
> proton-i18n post-install
[warning] Cannot find/write the directory node_modules/proton-translations, we're going to create it
...
[proton-i18n] ✔ installed latest translations available live for proton-mail-settings
```

**Comment by dhoko** [comment]
:heavy_check_mark: voilà lock is fine on settings

**Comment by vladimiry** [comment]
i18n stuff works for webclient project but not for any other project. For example `proton-mail-settings` project faces `Error: Invalid locale data format` runtime error if any non-english/not-default locale is set.

I was debugging the issue and it looks like react-based projects require different than used by webclient project locales format. `proton-mail-settings` uses `ttag` library which expects `{contexts: {...}}` format but `{"ru_RU":{...}}` has been generated during the build process and so `proton-mail-settings` project faces `Error: Invalid locale data format` runtime error trying to load the wrong locale data format via `ttag.addLocale` call.

I see though that https://beta.protonmail.com has proper locales generated for `proton-mail-settings` project. So apparently build process has to be improved.

Attaching demo screenshots of debug point set in `ttag.addLocale` call (`proton-mail-settings` project):
- app
  ![beta-app-ttag-addLocale-call](https://user-images.githubusercontent.com/1560781/75922544-3fedfc80-5e74-11ea-9ad1-3f927660d5b5.png)
  ![beta-app-local-code](https://user-images.githubusercontent.com/1560781/75922541-3ebccf80-5e74-11ea-8bf4-230a87b0ecc3.png)
- live
  ![beta-live-ttag-addLocale-call](https://user-images.githubusercontent.com/1560781/75922546-40869300-5e74-11ea-9138-c2b3fb3740ac.png)
  ![beta-live-local-code](https://user-images.githubusercontent.com/1560781/75922545-3fedfc80-5e74-11ea-883d-4a7e60527af4.png)

**Comment by dhoko** [comment]
There is a bug inside proton-i18n, but you can install the correct locales if you use the .env


cf 

Webclient .env:
```
I18N_DEPENDENCY_REPO=git@github.com:ProtonMail/proton-translations.git
I18N_DEPENDENCY_BRANCH=webmail
I18N_DEPENDENCY_BRANCH_V4=webmail-v4
``` 


proton-mail-settings .env:
```
I18N_DEPENDENCY_REPO=git@github.com:ProtonMail/proton-translations.git
I18N_DEPENDENCY_BRANCH=fe-mail-settings
``` 

proton-contatcs .env:
```
I18N_DEPENDENCY_REPO=git@github.com:ProtonMail/proton-translations.git
I18N_DEPENDENCY_BRANCH=fe-contacts
``` 

proton-calendar .env:
```
I18N_DEPENDENCY_REPO=git@github.com:ProtonMail/proton-translations.git
I18N_DEPENDENCY_BRANCH=fe-calendar
```

**Comment by vladimiry** [comment]
Can confirm that adding above-listed env variables solves the issue :+1:

**Comment by vladimiry** [comment]
Looks like the issue missed to be closed, fixing now,
