### ISSUE TITLE
Add email count to draft folder

### ISSUE THREAD

**Issue by OddHouseGames** [ProtonMail/WebClients#178]
Add ability for draft folder to show email count to increase parity with all other mainstream mail applications.

The draft folder is meant to indicate unfinished items and prompt a user to complete and send over time, vs the current system of having no indication of draft folder contents.

**Comment by JulienPalard** [comment]
+1, having the number of "unread" draft is meaningless, having the number of drafts is meaningfull :)

I often find tens of drafts of already sent emails in my draft folder, probably due to a sync bug somewhere, I would enjoy "learning" their existance soon, instead of three month later wondering if it was sent or not :P

**Comment by OddHouseGames** [comment]
What's the status for this one? Not considering implementation?

**Comment by mmso** [comment]
This issue was closed as part of the migration to the new React codebase and mono-repository for Proton webapps. You are welcome to submit feature requests to https://protonmail.uservoice.com/forums/284483-protonmail and bug reports to https://protonmail.com/support/

**Comment by OddHouseGames** [comment]
When you search for something on user voice, you can't even search by 'most votes?'

**Comment by JulienPalard** [comment]
> the new React codebase

Is it open-source?

**Comment by dhoko** [comment]
@JulienPalard yep, it's this repository ;)

**Comment by JulienPalard** [comment]
@dhoko So if you don't move the repository why closing an unfixed issue?

**Comment by dhoko** [comment]
This repository used to host our old (Angular) version of the app. It is now hosting the new React monorepo (_known to users as version 4_). All the issues that existed here for the Angular version has been closed when we did the migration.

If you need to create a bug report or for a new feature we give you the links there https://github.com/ProtonMail/WebClients/issues/new/choose
