### ISSUE TITLE
Add 2 factor authentication

### ISSUE THREAD

**Issue by zafar-saleem** [ProtonMail/WebClients#18]
As a user, I would like to be able to enable 2 factor authentication to my protonmail account.

When 2 factor authentication is enabled, then upon logging into my protonmail account, I should/must be asked for second factor authentication with SassPass/ G authenticator mobile apps.

As a user, when I change any settings such as password etc in protonmail account then I should be asked for 2nd factor authentication. I should not be able to change any of my details without properly get authenticated via 2 factor authentication.

**Comment by bartbutler** [comment]
This is coming very very soon.
