### ISSUE TITLE
make it easy to use as a progressive web app

### ISSUE THREAD

**Issue by ExpandingMan** [ProtonMail/WebClients#185]
**Is your feature request related to a problem? Please describe.**
I think the version currently on beta.protonmail.com is great, and strongly prefer it to the android app, which is not nearly as nice.  4.0 on beta.protonmail.com currently works beautifully as a PWA, except for one major problem: it always logs you out.  That behavior might be a fine security feature for browsers, but for a mobile app it's maddening.  I think having a PWA is preferable to the android app anyway, even if the android app were changed to be some sort of "wrapper" for the PWA (I'm not a web or mobile developer, so I really don't know how that stuff works) because PWA's work seamlessly on any free hardware, and currently I'm not sure if the android app is easily obtainable outside of google's store.  Of course, the PWA needn't be tied to any store at all.

**Describe the solution you'd like**
Somehow the PWA would save a persistent session.  Again, my web knowledge is pretty limited, so I'm not sure what the solution would be, or what exactly the thinking is behind the current approach of always invalidating the cookies (i.e. what is the specific security concern?).  I would imagine that since PWA's must cache *something* that it should be possible to cache credentials along with the PWA separately from the browser's normal cookie cache, but I don't really know what I'm talking about.

**Describe alternatives you've considered**
Presumably there's some way for the android app to use a browser back-end so that we can benefit from all the great work that's being done on the web app in android, but, for reasons explained above, I think it would be beneficial to have a practical PWA regardless.

**Additional context**
Again, 4.0 works really nicely as a PWA, as a user I don't see any obvious problems with protonmail as a PWA except for this session persistence issue.

**Comment by bartbutler** [comment]
The session persistence issue is something we are going to solve generally for the web apps, especially as we add multiple web applications and share sessions between them. This should address your concerns here. As a side note, the Android app is now open source and thus obtainable outside the Google Play Store:

https://github.com/ProtonMail/proton-mail-android
