### ISSUE TITLE
[feature request] v4 missing one click "empty trash" button

### ISSUE THREAD

**Issue by vladimiry** [ProtonMail/WebClients#189]

**Comment by dhoko** [comment]
:wave: 

You have an option, inside the dropdown _Advanced Options_ on the right side of the toolbar.
cf -> 
![Screenshot from 2020-06-12 11-08-22](https://user-images.githubusercontent.com/713283/84486034-1aeffd80-ac9d-11ea-8012-cb5f06cf1508.png)

**Comment by vladimiry** [comment]
Thanks for pointing me to this :+1: I think it's reasonable to be hidden under the menu so user doesn't click it accidentally.
