### ISSUE TITLE
Display a failure message when the DNS server of the receiver is unreachable.

### ISSUE THREAD

**Issue by lypwig** [ProtonMail/WebClients#19]
### Context

Nothing to put here, server-sided issue (but I don't know on which repository send this issue).

### What steps will reproduce the problem?

1) With any mail client, send a mail to someone whose the DNS server of its mail is unreachable.

### What is the expected result?

An error message, like:

> Delivery to the following recipient failed permanently: foo@bar.com

### What happens instead?

Nothing

**Comment by bartbutler** [comment]
You get a bounce message in your inbox if you do this, which I think is fairly standard result. I did, trying it just now. I suppose we could do an MX lookup during send for each recipient first but that could get expensive fast.

**Comment by lypwig** [comment]
Ok sorry, I did not try with that email, I give an accurate issue.

The fact is I recently started to update the DNS server of my mail (let *foo@bar.com*) host, so for a short time (during DNS modification) there is no DNS server associated with the mail but the mail *foo@bar.com* still exists.

During this time:
- when I send a mail to *foo@bar.com* from a gmail address, I receive a *delivery mail failure* ;
- when I send a mail to *foo@bar.com* from protonmail client, nothing appends.

Please reopen.
