### ISSUE TITLE
Using command-enter or control-enter to send email

### ISSUE THREAD

**Issue by asuh** [ProtonMail/WebClients#191]
**Is your feature request related to a problem? Please describe.**
When I compose a new email, I became accustomed to using keystrokes to send email instead of using the Send key. It appears Protonmail doesn't support a keystroke for this action.

**Describe the solution you'd like**
Use the keystroke cmd-enter (Mac) or ctrl-enter (Win) to send the mail. This would a duplication of the click event for the "Send" button.

**Comment by dhoko** [comment]
:wave: 

Hum, we already have this feature available 
![Screenshot from 2020-06-26 15-44-00](https://user-images.githubusercontent.com/713283/85863945-29bdd080-b7c4-11ea-9771-a29d7836e4ea.png) 
Maybe you need to enable the keyboard shortcuts ->  https://mail.protonmail.com/account

**Comment by asuh** [comment]
You're right, I never saw this.

I'm using beta and it's here:
https://beta.protonmail.com/settings/general

I wish I didn't have to dig for this to enable it. Any reason not to enable by default?

**Comment by asuh** [comment]
I am now using Protonmail 4.0 Beta 30 and command-enter/control-enter doesn't appear to be working for me even with Keyboard shortcuts enabled.

Firefox 82.0.3 on macOS 10.13.6 and Windows 10 20H2. Same problem on both OSes and browsers.
