### ISSUE TITLE
Self sent emails now show up as two in web app

### ISSUE THREAD

**Issue by foodiesgit** [ProtonMail/WebClients#195]
## Expected Behavior
Sent copy should be ignored as the sender and receiver are the same.

## Actual Behavior
Showing up as different emails with (2) in front of the conversation. This is not the same issue with different mailboxes as was raised in the past.

## Steps to Reproduce the Problem

  1. send email to self.
  2. reload protonmail page.
  3. see email show up as 2 unread messages.

## Specifications

  - Version: web
  - Platform: both main and beta
  - URL:

**Comment by foodiesgit** [comment]
LE: sent copy should at least show up as read by default else you need to read both emails to have the conversation appear as read.

**Comment by bartbutler** [comment]
This bug was introduced in a refactor on Tuesday. It should now be fixed. Thanks for the report!
