### ISSUE TITLE
Expand all

### ISSUE THREAD

**Issue by ghost** [ProtonMail/WebClients#2]
I see that ProtonMail now has conversation view, the first such client besides Gmail I am aware of.

Also similar to Gmail is all messages are collapsed except for unread.

However Gmail has an "Expand all" button, and ProtonMail appears to lack this. So if you wish to reread the entire conversation, you have to click every message that has already been read.

**Comment by EpokK** [comment]
Every time the user opens a message, the web application decrypts the content thereof. This takes time and uses the web browser (performance). So apply this process to a conversation containing multiple messages is not possible now.

**Comment by ghost** [comment]
I am reposting this as @EpokK removed it, and it seems helpful:

> Every time the user opens a message, the web application decrypts the content thereof. This takes time and uses the web browser (performance). So apply this process to a conversation containing multiple messages is not possible now.

**Comment by EpokK** [comment]
We can improve it by decrypting the message content, one by one. Probably a future feature.

**Comment by artem-zinnatullin** [comment]
Would be great to have this implemented one way or another, long unread chains become such a pain to read (scroll, click, wait, read, repeat)… (GitHub emails is a good example)

**Comment by mkasprz** [comment]
I made a quite dirty (especially with all this `sleep`s) workaround (javascript with some of jquery). I would be happy if it could help anyone.
```javascript
function sleep(timeout) {
    return new Promise(resolve => setTimeout(resolve, timeout));
}

async function onKeyDown(event) {
    if (event.ctrlKey && event.code == "KeyO") {
        var newEvent = document.createEvent('Events');
        newEvent.initEvent('mouseup', true, false);
        var shouldHideDetails = event.shiftKey;
        $('.summary').filter((index, element) => $(element.parentNode).has('.details').length == shouldHideDetails).each((index, element) => element.dispatchEvent(newEvent));

        var scrollTop = $('#pm_thread').scrollTop();
        await sleep(400);
        while($('#pm_loading.show').length) {
            await sleep(200);
        }
        while(scrollTop != $('#pm_thread').scrollTop()) {
            scrollTop = $('#pm_thread').scrollTop();
            await sleep(200);
        }
        $('#pm_thread').scrollTop($('article:last').offset().top - $('#pm_thread').offset().top + $('#pm_thread').scrollTop() - 10);
    }
}

document.onkeydown = onKeyDown;
```
<kbd>Ctrl+O</kbd> opens all conversations and <kbd>Ctrl+Shift+O</kbd> closes all of them. It also scrolls to the last message afterwords (which is the worst part I believe).

I personally use it in Rambox and it's easy to inject javascript code there (and <kbd>Ctrl+O</kbd> is not used).

It obviously may not work in the future as DOM may change.

**Comment by mkasprz** [comment]
The issue got closed, but the requested feature in not implemented, right? Or is it?
