### ISSUE TITLE
Add SMTPUTF8 support

### ISSUE THREAD

**Issue by ghost** [ProtonMail/WebClients#200]
Could you please support SMTPUTF8 as defined in RFC 6531?

**Comment by mtlll** [comment]
This was closed as "completed" almost 4 years ago, so why can't I email an address with "æ" in it in 2025?

@mmso Care to comment?

**Comment by mmso** [comment]
Hi @mtlll, please refer to [uservoice](https://protonmail.uservoice.com/forums/284483-protonmail) for feature requests, otherwise your suggestion gets lost as we don't use github to track them.
