### ISSUE TITLE
Native UWP Client

### ISSUE THREAD

**Issue by mcarthurcolin** [ProtonMail/WebClients#204]
While there are native clients for Android and iOS, most people use email via PC or Mac. Native clients are needed.

Create a native UWP client for Windows.

I added this feauture request here bacause I'n not sure in which existing repository it should be.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/ProtonMail/WebClients/issues/204#issue-711802855

@mcarthurcolin, the Bridge should now service this purpose. However, @mmso, this should probably be closed as unplanned, since there exists no UWP/XAML client.
