### ISSUE TITLE
[feature request] Share "proton-account" web app

### ISSUE THREAD

**Issue by vladimiry** [ProtonMail/WebClients#205]
The one that got recently deployed at https://account.protonmail.com.

Also is this app going to be deployed at https://account.protonmail.ch (CH entry point) and https://account.protonirockerxow.onion (entry point via TOR)?

CC @dhoko

**Comment by vladimiry** [comment]
Looks like I could try building the web apps with `appMode=standalone` proton-pack/webpack arg and get the SSO mode disabled.

**Comment by dhoko** [comment]
:wave: 

Sorry, i forgot to change the visibility of the repo :facepalm: https://github.com/ProtonMail/proton-account
Hum, the beta is only on protonmail.com, not on the ch version. Same for tor today as account is part of the beta too, all apps are on a subdomain now.

To build the SSO we have an appMode `sso` so the apps are able to work on a subdomain.
Standalone mode is still possible if you want \<mail-webclient>/calendar etc.

Btw, no more "tricks" to get translations. `npm ci` is enough. We removed the hook, and it's a npm dep now.

**Comment by vladimiry** [comment]
Thanks for a fast and detailed feedback. Closing the issue as resolved. Might come back later when I have tried the updated projects in action.
