### ISSUE TITLE
Test email filter and apply to existing emails

### ISSUE THREAD

**Issue by edwinlai** [ProtonMail/WebClients#206]
**Is your feature request related to a problem? Please describe.**
I'd like have the ability to test run a filter on my existing email instead of waiting for new email to come. I'd also like to be able to apply the filter on existing email. Gmail offers both very elegantly.

**Describe the solution you'd like**
While setting up an email filter, allow the ability to test on existing email. Have another option at the end of the filter set up to apply to existing emails.

**Describe alternatives you've considered**
There isn't a work around in ProtonMail.

**Additional context**
From Gmail
<img width="391" alt="Screen Shot 2020-10-06 at 11 18 37 PM" src="https://user-images.githubusercontent.com/6708669/95294526-48534f00-082a-11eb-91ea-83d16902e4d2.png">

**Comment by markcellus** [comment]
why was this closed?

**Comment by utx0** [comment]
I cant find this feature in the app anywhere??

**Comment by Ventto** [comment]
Me neither :/
Why was the issue closed ?

**Comment by mmso** [comment]
This issue was closed as part of the migration to the new React codebase and mono-repository for Proton webapps. You are welcome to submit feature requests to https://protonmail.uservoice.com/forums/284483-protonmail
