### ISSUE TITLE
Allow for bulk selection of emails for a folder or filter

### ISSUE THREAD

**Issue by edwinlai** [ProtonMail/WebClients#207]
**Is your feature request related to a problem? Please describe.**
I'd like to bulk select emails in a folder rather than iterate through each page. For example, if I want to delete all emails in a given folder, I'd have to select all, then delete, navigate to the next page, and repeat.

**Describe the solution you'd like**
Google allows for the bulk selection of all emails in a folder (or filter).

**Describe alternatives you've considered**
The only work around is the Bridge and doing it in Mail.

**Additional context**
From Gmail
<img width="657" alt="Screen Shot 2020-10-06 at 11 25 15 PM" src="https://user-images.githubusercontent.com/6708669/95295043-37570d80-082b-11eb-8a6a-c6ab7dbf6e43.png">

**Comment by adriy-be** [comment]
Hi, this ticket is not completed !
Can you add this feature ? Requested also in [uservoice](https://protonmail.uservoice.com/forums/284483-proton-mail/suggestions/7840971-a-select-all-feature?page=1&per_page=20)

**Comment by ma1tech** [comment]
Hello,

i moved to protonmail and looking for the same feature.
Will it be avalaible in the future?
