### ISSUE TITLE
Auto delete of trash >30 days old

### ISSUE THREAD

**Issue by edwinlai** [ProtonMail/WebClients#208]
**Is your feature request related to a problem? Please describe.**
I have to manually empty my trash.

**Describe the solution you'd like**
I'd like for trash to automatically be emptied after 30 days. This is a feature of Gmail.

**Describe alternatives you've considered**
None

**Additional context**
From Gmail
<img width="578" alt="Screen Shot 2020-10-06 at 11 26 49 PM" src="https://user-images.githubusercontent.com/6708669/95295167-6e2d2380-082b-11eb-81ae-579a6883fa02.png">

**Comment by AlbanaCodes** [comment]
any progress?

**Comment by AlbanaCodes** [comment]
@mmso  I have seen people asking since 2015 for this basic feature that every other email provider offers. why is this issue closed without any consideration at all?

**Comment by mmso** [comment]
Hi @AlbanaCodes, please refer to userVoice for feature requests, otherwise your suggestion gets lost as we don't use github to track them.
