### ISSUE TITLE
Inbox shows large advertisement on login

### ISSUE THREAD

**Issue by stefanrua** [ProtonMail/WebClients#209]
**Describe the bug**
After logging in to ProtonMail, even as a "PLUS" user, the inbox displays a large ad.

**To Reproduce**
1. Log in to ProtonMail
2. Be disgusted by the huge ad

**Expected behavior**
The conversation box should be empty when no conversation has been selected.

**Screenshots**
![ad](https://user-images.githubusercontent.com/27307061/95973842-d5933680-0e1c-11eb-9d0c-4feefb31af83.png)

**Desktop:**
 - OS: Fedora Linux
 - Browser: Firefox
 - Version: 81.0.1 (64-bit)
 - Plugins: uBlock Origin, GNOME Shell integration
 - Resolution: 1920x1080
 - URL: mail.protonmail.com

**Additional context**
This bug has bothered people before, too:
 - [reddit: Is there any way to get rid of this "welcome" screen when I open ProtonMail in my browser?](https://www.reddit.com/r/ProtonMail/comments/am1jep/is_there_any_way_to_get_rid_of_this_welcome/)
 - [feedback forum: Remove the "welcome" screen in the web interface for paying customers.](https://protonmail.uservoice.com/forums/284483-feedback/suggestions/32830216-remove-the-welcome-screen-in-the-web-interface-f)

Client-side workaround using custom CSS:
```
#pm_latest {
display:none;
}
```

**Comment by darigovresearch** [comment]
Think this is a valid issue, many users may be turned off when seeing such an add after logging in or worse having paid for a subscription

**Comment by darigovresearch** [comment]
@mmso can you advise the reasoning for closing this issue?

**Comment by mmso** [comment]
This issue was closed as part of the migration to the new React codebase and mono-repository for Proton webapps. You are welcome to submit feature requests to https://protonmail.uservoice.com/forums/284483-protonmail and bug reports to https://protonmail.com/support/
