### ISSUE TITLE
Show multiple labels per email

### ISSUE THREAD

**Issue by Andras-Csanyi** [ProtonMail/WebClients#215]
**Is your feature request related to a problem? Please describe.**
Managing my email list subscriptions I add multiple labels to emails. It provides me the ability to oversee what emails I have and so on. But, protonmail displays only one label and the remaining are hidden. It is not good for me. In this form labels are not better than directories for me.

**Describe the solution you'd like**
Display more or all added labels for an email.
The other solutuon can be which label should be displayed and which is not. For example, I have a technical label "lists" which is used to mark all email lists I have and makes possible that I can easily select all emails from email list and delete them. I don't want to see this label, so that configurability of displayed labels would be great.

**Describe alternatives you've considered**

**Additional context**

**Comment by ghost** [comment]
@mmso I see this was closed as completed. Which PR resolved this? The issue still appears in 5.0.20.10.

**Comment by rcteske** [comment]
I am a user for the beta web client for some time now and as of 20/10/2023 I can't find an option like that on the settings. The comfortable density also doesn't change this, I only see one label per row (I use the maximized composer).

If there is any implementation to be done for this it is a good idea to sort all labels displayed alphabetically so they are actually useful at a glance.

**Comment by njnygaard** [comment]
To note, I see this issue as well in `5.0.35.3 ß` with the Row display on. In column display, multiple labels can be shown. This feature seems to fit better with Row display because there is more real estate to show labels generally.

**Comment by rcteske** [comment]
@Andras-Csanyi, is there a way to reopen this ticket? Gmail shows multiple (3 at least for sure) label tags next to the email title without a visualization pane (like the Proton Row display), it would be really useful to have this here too.

**Comment by Andras-Csanyi** [comment]
I don't see a button saying that "Reopen" or something like that. Probably a new ticket should be created, IMHO.

**Comment by deepsynergy** [comment]
@mmso This is extremely frustrating that only one label is displayed in browser per email. The issue has not been fixed. There is plenty of room in the row view.

**Comment by RheaAyase** [comment]
+1 opening a new ticket
