### ISSUE TITLE
Using `j` and `k` to navigate the row view email list

### ISSUE THREAD

**Issue by joelostblom** [ProtonMail/WebClients#22]
Currently, it is possible to navigate up and down the column view email list using <kbd>j</kbd> and <kbd>k</kbd>, if an email message is open.

In the row view, it is possible to open an email and then navigate to next and previous email with <kbd>j</kbd> and <kbd>k</kbd>. However, it is not possible to navigate up and down the list of emails in row view.

I think it would be great to be able to navigate the row view email list with <kbd>j</kbd> and <kbd>k</kbd>, in addition to using the arrow keys, and I wonder if this feature could be added to protonmail.

**Comment by EpokK** [comment]
Yes we will add it.

**Comment by EpokK** [comment]
Added.
