### ISSUE TITLE
Request: Yubikey integration

### ISSUE THREAD

**Issue by emileturcotte** [ProtonMail/WebClients#229]
**Is your feature request related to a problem? Please describe.**
I have a Yubikey which is tied to my public identity and I use it for a lot of my online accounts - except Protonmail. I am not fond of having to upload my private key into my web client, although I trust your security, and would prefer if the encryption operations could take place inside my Yubikey instead. Without this, my Protonmail keys are different from my public identity ones and this looks as if I am not who I pretend to be when I write emails to people.

**Describe the solution you'd like**
Protonmail could allow uploading only my public key into the web client and associate it with my email addresses. When opening my mailbox or sending an email, the client could prompt my Yubikey for encryption operations. This could also potentially allow me to sign and encrypt my emails in Thunderbird without the need of a bridge.

The possibility of managing my own encryption keys locally, without having to upload private keys to some external server, is a big deal for me, and surely for many people out there also. Thank you for your consideration.

**Comment by bartbutler** [comment]
While not impossible, there is very little chance of this becoming a development focus in the near or medium term, as it is a very niche use case and would break one of Proton's main advantages: automatic, safe, keyring distribution to multiple devices. Sorry :(
