### ISSUE TITLE
Protonmail automatically inserting "Reply-To" field

### ISSUE THREAD

**Issue by JambonBeurreVodka** [ProtonMail/WebClients#234]
When I send an email from Gmail, the recipient will see a "From" field.

When I send an email from Protonmail, the receipient will see a "From" field and a "Reply-To" field, both of them pointing to the same email address (email of the sender).

I thought it was a bug with Protonmail bridge but I tried it also with the webmail and from 2 different accounts and it always inserts "Reply-To". Emails look less clean like that, is there a way to disable that?

**Comment by bartbutler** [comment]
I forget the details but we do this for compatibility with some email service providers, and as headers are not usually shown in email clients unless they are relevant. Which client are you having trouble with? Or do you just not like the presence of the redundant header?

**Comment by JambonBeurreVodka** [comment]
I just don't like the presence of this redundant header and I notice it when it comes from someone else. And Gmail doesn't need to set the "Reply-To" field to be compatible with every providers, so I don't get why Protonmail would need this field to be compatible.
