### ISSUE TITLE
Don't let free users create filters

### ISSUE THREAD

**Issue by Sigafoos** [ProtonMail/WebClients#24]
Free users can see the filter tab and can go through the steps of creating new filters. This is a Plus feature, however, so the save button will always be greyed out.

This is not communicated to the user in any way: the button is simply not clickable. Ideally, the "Add Filter" and "Clear All" buttons should be replaced with a call to action to upgrade.

**Comment by bartbutler** [comment]
Pretty sure free users are allowed to create one filter. If the Save button is greyed out, it's probably not a valid filter (either no actions, or the conditions are invalid).

**Comment by Sigafoos** [comment]
Aha. I was adding a second condition (if sender is X or recipient is X).

In that case, disable the "Add Condition" button?

**Comment by bartbutler** [comment]
You should be able to add a second condition...

**Comment by Sigafoos** [comment]
Here's with one condition:

![active](https://cloud.githubusercontent.com/assets/417845/23779172/d5937c98-050c-11e7-8c4e-866270ca09df.PNG)

Adding a second:

![inactive](https://cloud.githubusercontent.com/assets/417845/23779174/de310a00-050c-11e7-81dd-41f2fc5a543e.PNG)

I'm also seeing `disabled` getting added/removed to the save button in the DOM when I add/remove the second condition.

**Comment by bartbutler** [comment]
This UI really needs to be improved. Try hitting the enter key with your cursor in the 'two' text box, or clicking the + next to it.

**Comment by Sigafoos** [comment]
Aha! That did it.

**Comment by janveverka** [comment]
+1 to improve the Filters UI. I've just stumbled across this too!!

**Comment by EpokK** [comment]
This is fixed.

**Comment by agatakotecka** [comment]
> Free users can see the filter tab and can go through the steps of creating new filters. This is a Plus feature, however, so the save button will always be greyed out.
> 
> This is not communicated to the user in any way: the button is simply not clickable. Ideally, the "Add Filter" and "Clear All" buttons should be replaced with a call to action to upgrade.

Fuck you. Filters should be available to all users, it's basic need like food, water etc
