### ISSUE TITLE
Mark email as read on mobile

### ISSUE THREAD

**Issue by KaKi87** [ProtonMail/WebClients#247]
ProtonMail web allows marking an email as ***un*read** on both desktop and mobile, but allows to mark one as **read** only on desktop, although there's place for it on mobile.

![](https://i.redd.it/hlqcmmc6ym071.jpg)

[Reported on Reddit](https://old.reddit.com/r/ProtonMail/comments/niebvn/mark_email_as_read_on_betaprotonmailcom_on_mobile/) two months and a half ago.

Thanks

**Comment by mmso** [comment]
You are welcome to submit feature requests to https://protonmail.uservoice.com/forums/284483-protonmail and bug reports to https://protonmail.com/support/
