### ISSUE TITLE
Unable to locate the deployed git commits

### ISSUE THREAD

**Issue by vladimiry** [ProtonMail/WebClients#249]
I run the `git show <commit>` for the commits taken from the deployed versions info and get the `fatal: bad object <commit>`-like result.

Deployed versions info taken from here:
https://account.protonmail.com/assets/version.json
https://drive.protonmail.com/assets/version.json
https://calendar.protonmail.com/assets/version.json
https://mail.protonmail.com/assets/version.json

It's required to be able to checkout/reset to the exact deployed repository commit so please make the adjustments.

**Comment by mmso** [comment]
We filter out sensitive parts of the repository before it's published to github, so the exact sha is not relevant. What is relevant is the `branch` field, e.g. `proton-account@4.5.1` (though we should probably rename this to tag). Which represents the same thing and is what you should use.

**Comment by vladimiry** [comment]
Thanks.

It's not apparent to strangers how to correlate the exact repository commit and deployed commit so I think the first impression an average developer would get is that things look a little shady/fishy.

I agree naming the branch like `proton-account@4.4.0-<commit>` would bring some more clarity.

I see that version.json includes the `branch` field, so that should be enough.

**Comment by vladimiry** [comment]
> I agree naming the branch like proton-account@4.4.0-<commit> would bring some more clarity.

Or maybe even `proton-account@4.4.0-private-<commit>` (private/internal/hidden/etc).
