### ISSUE TITLE
Backends?

I can't get to sleep without at least asking the question. Van these clients work with backends other than ProtoMail?

### ISSUE THREAD

**Issue by chris2fr** [ProtonMail/WebClients#250]
>  We are happy to answer your questions about the code or discuss technical ideas. 
 
Please complete the following checklist (by adding [x]):
- [x] I have searched open and closed issues for duplicates
- [x] This isn't a feature request
- [x] This is not a report about my app not working as expected

----------------------------------------

**Comment by mmso** [comment]
If this is referring to self-hosting the Proton backend, please see the answer in  https://github.com/ProtonMail/WebClients/issues/257#issuecomment-964240013

Otherwise, yes it would be technically possible for these clients to work on other backends compatible with the ProtonMail API.
