### ISSUE TITLE
The source code of the live/deployed/production client version has not been published to github.

### ISSUE THREAD

**Issue by vladimiry** [ProtonMail/WebClients#251]
>  We are happy to answer your questions about the code or discuss technical ideas. 
 
Please complete the following checklist (by adding [x]):
- [x] I have searched open and closed issues for duplicates
- [x] This isn't a feature request
- [x] This is not a report about my app not working as expected

----------------------------------------

It was [said before](https://github.com/ProtonMail/proton-mail/issues/75#issuecomment-864368151) that after moving to monorepo the published to github code won't have to catch up with the live/deployed version but it's still the case.

**To reproduce**:

The https://mail.protonmail.com/assets/version.json shows `proton-mail@4.5.8` branch/tag but the `git reset --hard proton-mail@4.5.8` command ends up with the `fatal: ambiguous argument 'proton-mail@4.5.8': unknown revision or path not in the working tree.` error.

**Comment by mmso** [comment]
We apologize for this @vladimiry. This time the automated setup was bypassed due to an internal issue. The latest builds were pushed right now, and should normally follow the automated setup in the future.

**Comment by vladimiry** [comment]
Thanks. Good to know that the automated setup is taking place now and that its flaw got revealed and fixed.
