### ISSUE TITLE
[TYPO] Typo in the README.md file

### ISSUE THREAD

**Issue by alexis-opolka** [ProtonMail/WebClients#252]
Hello, I assume that the name of this repository has been changed hence the command for cloning it is now incorrect.

It should be `git clone git@github.com:ProtonMail/WebClients.git` instead of `git clone git@github.com:ProtonMail/web-clients.git`.
It's the same for cloning the repository using HTTPS protocol. (`git clone https://github.com/ProtonMail/WebClients.git` instead of `git clone https://github.com/ProtonMail/web-clients.git`)

**Comment by mmso** [comment]
Thanks for the report. Should be updated now.
