### ISSUE TITLE
[blocker] How to properly complete "yarn install" command doing local build (not on CI)?

### ISSUE THREAD

**Issue by vladimiry** [ProtonMail/WebClients#254]
The `yarn install` execution currently ends up with `YN0000: command not found: packages/config/install` error.

`postinstall` runs `config-app` script which executes the `packages/config/install` script which is not published here (there is no `config` directory in https://github.com/ProtonMail/WebClients/tree/main/packages).

https://github.com/ProtonMail/WebClients/blob/a2bb50f19f7f2ec55c2a3858532af3dcaa0ea2bb/package.json#L14

https://github.com/ProtonMail/WebClients/blob/a2bb50f19f7f2ec55c2a3858532af3dcaa0ea2bb/package.json#L11

**Comment by vladimiry** [comment]
@mmso what is the purpose of that `postinstall` script run? Asking since I guess it might not be required for everyone and so I will just drop it then before building the stuff.

**Comment by vladimiry** [comment]
Is anybody home? This looks like a blocker.

CC @bartbutler.

**Comment by mmso** [comment]
Thanks for the report @vladimiry 

We pushed something that should fix this

**Comment by vladimiry** [comment]
@mmso thanks for the fix. So the guess was correct, that script run can be ignored. I will have to explicitly ignore/wipe it for now in my build pipeline since I reference the [tags](https://github.com/ProtonMail/WebClients/tags) and those were not yet updated with the fix.
