### ISSUE TITLE
Incorrect Message in Dialog Box When Changing Mailbox Password

### ISSUE THREAD

**Issue by saurabh-mish** [ProtonMail/WebClients#262]
I recently changed my login password followed by the mailbox password.

When changing the login password, a dialog box opens up asking for "Old login password", "New login password", and "Confirm login password". This is straight-forward.

When changing the mailbox password, a dialog box opens up asking for the same details - "Old login password", "New login password", and "Confirm login password". I think this is incorrect because when I entered the old login password, it didn't work, and I had to enter the current login password.

The dialog box for "Change mailbox password" should replace the field "Old login password" with "Current login password".

**Comment by StraightOuttaCrompton** [comment]
Thank you for the report. We are looking into this.

**Comment by mmso** [comment]
Fixed in https://github.com/ProtonMail/WebClients/commit/82c996cc23d2de5410928d70d88e10b3d1bbd218
