### ISSUE TITLE
No priority support for PRO customers

### ISSUE THREAD

**Issue by nick-fullstack-dev** [ProtonMail/WebClients#263]
I am a PRO customer, I can no longer send an email from my professional email address because my IP address was blocked by protonmail. My professional activity is paralyzed. I made a request for support it 48 hours and I received no response. Is that what you call Priority Support for PRO customers? Here is the ticket number 940607

**Comment by bartbutler** [comment]
Most of our support staff is in eastern Europe and this weekend is Orthodox Christmas, so they are understaffed and response times will be slower, sorry. I'll ping someone about your ticket and see what we can do.
