### ISSUE TITLE
No priority support for PRO customers

### ISSUE THREAD

**Issue by nick-fullstack-dev** [ProtonMail/WebClients#264]
I am a PRO customer, I can no longer send an email from my professional email address because address was blocked by protonmail. My professional activity is paralyzed. I made a request for support it 72 hours and I received no response. Is that what you call Priority Support for PRO customers? Here is the ticket number 940607

**Comment by bartbutler** [comment]
I escalated the issue internally and will ping again. Please stop creating issues on our repositories.

**Comment by nick-fullstack-dev** [comment]
This is the only way to get your attention. This situation is not normal.

**Comment by nick-fullstack-dev** [comment]
I've been patient for more than 3 days.

I am obligated to request assistance through the Github website for staff to PING to your service so that you take my request into consideration.

For 3 days I have been getting the same answer: that my request will be transferred to another service.

I can't even answer you, I have to use the contact form on your website.

This is not serious.

I can no longer use my professional address and my professional activity is paralised. I will seek damages and interest in court for the economic loss I suffered.
