### ISSUE TITLE
Where is "Key Transparency" package hosted?

### ISSUE THREAD

**Issue by paulmillr** [ProtonMail/WebClients#266]
>  We are happy to answer your questions about the code or discuss technical ideas. 
 
Please complete the following checklist (by adding [x]):
- [x] I have searched open and closed issues for duplicates
- [x] This isn't a feature request
- [x] This is not a report about my app not working as expected

----------------------------------------

I've noticed there is a key transparency package in the repository. I was not able to find any mentions to it in google or at PM website. Where do you host it?

**Comment by ghost** [comment]
Hi Paul. Key Transparency is a feature under active development. As you have already noticed, a [very first draft](https://github.com/ProtonMail/WebClients/tree/main/packages/key-transparency) of the client's code already exists in our codebase but is currently unused by the client. Any further detail on its functionality and functioning will need to wait until we have completed development, I'm afraid.
