### ISSUE TITLE
Convert plain text links to real links automatically

### ISSUE THREAD

**Issue by karolchmist** [ProtonMail/WebClients#27]
Some sites send links in HTML formatted mail without marking them as such. 

Example :
```html
Hello,<br>
<br>
Here is the link.<br>
<br>
https://www.example.com/interesting.html<br>
<br>
```

Gmail detects and converts them automatically to clickable <a> links. 

It would be great if ProtonMail could provide similar function.

**Comment by EpokK** [comment]
It's done.
