### ISSUE TITLE
Inconsistency in contacts icons

### ISSUE THREAD

**Issue by ildede** [ProtonMail/WebClients#270]
>  We are happy to answer your questions about the code or discuss technical ideas. 
 
Please complete the following checklist (by adding [x]):
- [x] I have searched open and closed issues for duplicates
- [x] This isn't a feature request
- [x] This is not a report about my app not working as expected

----------------------------------------

I notice that there is an inconsistency in filling of "Contacts" icon trough different apps.

ProtonMail:
![Schermata 2022-03-30 alle 12 37 33](https://user-images.githubusercontent.com/3754465/160813810-5069617f-2994-4296-ba0c-5e189038a725.png)

ProtonDrive, ProtonCalendar:
![Schermata 2022-03-30 alle 12 52 11](https://user-images.githubusercontent.com/3754465/160815424-9ff63ed7-c089-4780-be99-2a8e64c65f45.png)

I'm not sure if this is right or not, in case this isn't right: can I try to dive into this and make a small pull request?

**Comment by econdepe** [comment]
Hey @ildede, yeah, this is happening because Drive and Calendar are using a slightly outdated version of the icon, but they will catch up quite soon! You can see that in the beta version of Calendar (4.0.9), the icon is already aligned with the Mail one.

Thanks for the report at any rate! :)

**Comment by ildede** [comment]
Oh yes, it's true =)

Thanks!
