### ISSUE TITLE
Login form submitting ends up with "StatusCodeError: Not Found" error

### ISSUE THREAD

**Issue by vladimiry** [ProtonMail/WebClients#271]
This email is used as a contact point for [ElectronMail](https://github.com/vladimiry/ElectronMail/blob/075a8aca0fe52bd8608ee216a2f5f28ca4220331/package.json#L5) project.

What is the problem there? Does it mean that the account got mistakenly removed/locked? If so, can it be re-enabled? There is no long "inactivity" period as this account was used at least once per week.

PS Could not locate other way to place the issue, like via customer support, since the account appears to be locked without any notice.

**Comment by bartbutler** [comment]
You didn't specify the email, but are you using Electron mail pointed at the Tor API endpoint by any chance? We've migrated the Tor site to v4 of the web client so you need to use the mail subdomain if that's the case. We disconnected the parent Tor domain API endpoint today for infrastructure reasons.

**Comment by vladimiry** [comment]
> You didn't specify the email

It's available by the link in the original message.

> but are you using Electron mail pointed at the Tor API endpoint by any chance? 

I'm, yes. Thanks for the direction. Looks like I should have spent some time doing debugging before placing the issue, my apologies.

**Comment by bartbutler** [comment]
Ah sorry, should have clicked the link. Sorry for the inconvenience!

**Comment by vladimiry** [comment]
Can confirm it works as expected after updating/mapping the web clients to a new domain.
