### ISSUE TITLE
Inconsistent color palettes when creating and editing folders and labels

### ISSUE THREAD

**Issue by 0x6d6c** [ProtonMail/WebClients#279]
- [x] I have searched open and closed issues for duplicates
- [x] This isn't a feature request
- [x] This is not a report about my app not working as expected

----------------------------------------

Hi,
I've noticed that the color palette for new folders and labels differs depending on from where the folder/label is created:
1. In the **Inbox view**, when cliking `+` icon the color palette is "richer" and offers 20 colors to choose from: 4 rows x 5 colors:
    - ![image](https://user-images.githubusercontent.com/4584067/178252079-b7436b51-bd39-4e34-a423-92f8e4a8ef27.png)
    - ![image](https://user-images.githubusercontent.com/4584067/178252238-673be5d5-9645-4734-930d-34b2ef7501e3.png) 
3. In the **Settings view**, when clicking 'Add folder' or 'Add label`, the color palette is "poorer" and offers only 10 colors: 2 rows x 5 colors:
    - ![image](https://user-images.githubusercontent.com/4584067/178252858-0afb6c28-fef1-4481-b9f8-acffafced4d5.png)
    - ![image](https://user-images.githubusercontent.com/4584067/178253009-3cfe9e31-8785-4468-918b-8dcb33488a2d.png)

When editing folders/labels the palette is also "poorer" even if the color has been chosen from the "richer" palette:

this → ![image](https://user-images.githubusercontent.com/4584067/178253759-9d01ea22-6882-4455-8faf-03282201a825.png)

becomes this → ![image](https://user-images.githubusercontent.com/4584067/178254905-2abe9054-afb3-4e8c-9bef-5ad418f6fbbc.png)

**Comment by StraightOuttaCrompton** [comment]
Hi @mi6th, thank you for reporting this issue.

We have a fix prepared which will deployed in a future version.

**Comment by 0x6d6c** [comment]
It's fixed, thank you :)
