### ISSUE TITLE
Add view with starred messages at the top

### ISSUE THREAD

**Issue by karolchmist** [ProtonMail/WebClients#28]
It would be great to have configurable sections in the inbox. For example, first a group of starred messages, then the rest of messages. It would be easier to not forget treating the starred messages.

**Comment by EpokK** [comment]
@karolchmist But if you go to the starred folder, you have more or less the same result right?

**Comment by karolchmist** [comment]
@EpoKK Well, I need to remember to go to the starred folder, which I do not often enough. It would be easier to remember to respond to starred mails by having them at the top of the inbox. 

In Gmail you can customize your view and have different sections in one single view (unread, starred, all etc).

Hope this helps, but you can close the issue if you find it not important enough.

**Comment by EpokK** [comment]
We don't plan to do that for now since it's possible to go to the starred folder to do the same action.
