### ISSUE TITLE
How to generate translation JSON files?

### ISSUE THREAD

**Issue by xet7** [ProtonMail/WebClients#281]
>  We are happy to answer your questions about the code or discuss technical ideas. 
 
Please complete the following checklist (by adding [x]):
- [x] I have searched open and closed issues for duplicates
- [x] This isn't a feature request
- [x] This is not a report about my app not working as expected

----------------------------------------

Hi,
Do you have some script that can convert Crowdin translations, from translator downloadable file format, to JSON format that is used in this repo ProtonMail etc? Where is that script? I tried to create bash script for it, but I did not get it working well enough yet.

I'm trying to test fi_FI.json translation, does web UI have enough space for words, does it look correct, or should I change to shorter words, or submit pull request to React UI template code to fix it?

**Comment by dhoko** [comment]
Hey :wave: 

We use [ttag-cli](https://github.com/ttag-org/ttag-cli) to extract strings and build them. Ex we  build the json file from the gettext via `npx ttag po2json '{file_path}' --format=compact -p`. 

> I'm trying to test fi_FI.json translation

We don't work with the JSON itself but with gettext files sent to crowdin, if you want to fix translation you can join us on crowdin and fix this language there, thx cf  https://github.com/ProtonMail/WebClients#help-us-to-translate-the-project 

This summary inside the readme needs an update :fearful:  
- if you want to fix proton drive it's inside this crowdin https://crowdin.com/project/ProtonDrive, 
- calendar is inside proton mail crowdin 
- proton-account is here https://crowdin.com/project/proton-core-localization

thx :pray:
