### ISSUE TITLE
How to use Human Verification when testing translation?

### ISSUE THREAD

**Issue by xet7** [ProtonMail/WebClients#285]
> We are happy to answer your questions about the code or discuss technical ideas.

Please complete the following checklist (by adding [x]):

-   [x] I have searched open and closed issues for duplicates
-   [x] This isn't a feature request
-   [x] This is not a report about my app not working as expected

---
Hi ! I was previously able to try Finnish translation this way:
https://github.com/wekan/wekan/wiki/ProtonMail

But not that you have added Human Verification, how can I login? Verification fails.

Related #281 #284

**Comment by xet7** [comment]
I also tried:
```
NODE_ENV=development yarn workspace proton-mail start
```
But it says unsupported browser, with link to:
https://proton.me/support/recommended-browsers

I tried with some of those browsers, and they still show "unsupported browser"

**Comment by mugiwarafx** [comment]
Hi, @xet7!

> I also tried:
> 
> ```
> NODE_ENV=development yarn workspace proton-mail start
> ```
> 
> But it says unsupported browser, with link to: https://proton.me/support/recommended-browsers
> 
> I tried with some of those browsers, and they still show "unsupported browser"

Are you trying to access the URL of your local network instead of the localhost URL? 

I will try to help if you provide more details about this specific issue.

Best,
Jordi

**Comment by mmso** [comment]
Let us know if you still have issues

**Comment by xet7** [comment]
@mmso

How do you convert translation webapp.xcliff to JSON now that .po file is not available anymore?

I previously converted .po files:
https://github.com/wekan/wekan/wiki/ProtonMail

I tried to look at some converterts at https://npmjs.com but I do not know what you use.

I will also try to test Finnish translation again, is it possible to test, when I get correct translation file format JSON.

**Comment by dhoko** [comment]
@xet7 I pushed what we use to convert the xliff back to ttag JSON https://github.com/dhoko/xliff-to-JSON-ttag 

We don't use gettext anymore as it was creating duplicates issues for us during translations.

**Comment by xet7** [comment]
@dhoko @mmso 

Thanks! Running Protonmail frontend with Finnish translations now works for me.
I added fixed instructions and screenshot to:
https://github.com/wekan/wekan/wiki/ProtonMail
