### ISSUE TITLE
U2F WebAuth question

### ISSUE THREAD

**Issue by okonon** [ProtonMail/WebClients#293]
-   [x] I have searched open and closed issues for duplicates
-   [x] This isn't a feature request
-   [x] This is not a report about my app not working as expected

---
Are there any plans to support WebAuth with Passkeys in addition to USB Security keys?

Basically Proton allows users to add Passkey (as well as as USB security keys) in Brave/Chrome:

* Click Settings > Account and password > Security key toggle
* Click "Try another way" button on Brave/Chrome's "Create a passkey for proton.me":
<img width="716" alt="Screenshot 2022-12-20 at 10 28 33" src="https://user-images.githubusercontent.com/1832398/208714193-d1ba5819-4b09-40a7-bafa-2bdfaf6c0663.png">

* Click "A different device" button. 
* "Choose how you want to create a passkey for proton.me" view will be shown.
<img width="490" alt="Screenshot 2022-12-20 at 10 25 52" src="https://user-images.githubusercontent.com/1832398/208714235-ea4b1232-127b-40ed-b3f7-048f8a1fb8a0.png">

* Add passkey to different device like an iPhone.

* Log out. 

* Attempt to sign in again. 

* After entering username/pass 2FA Proton page will be shown only showing USB option (there is no way to choose "other device"):
<img width="458" alt="Screenshot 2022-12-20 at 10 19 48" src="https://user-images.githubusercontent.com/1832398/208714372-58ae3c87-d13b-4e31-bab1-e1bd3261a50b.png">

Expected result is to choose "other device" and use previously used passkey stored on an iPhone.

Github supports this on Brave/Chrome when logging in:

* Login to github with usename/pass
* "Two-factor authentication" GitHub page will be shown, click "Use security key" button.
<img width="496" alt="Screenshot 2022-12-20 at 10 40 22" src="https://user-images.githubusercontent.com/1832398/208714611-6079a2cc-25ad-4d2b-9299-7136ab32633f.png">
* "Use your passkey" dialog with "A different device" will be shown allowing use to login with passkey stored on a phone:
<img width="706" alt="Screenshot 2022-12-20 at 10 40 38" src="https://user-images.githubusercontent.com/1832398/208714866-8eca5613-71fd-4f1d-8e35-7f65da3861ad.png">

Judging by GitHub's url i think it works on github because they use WebAuth. So the question is does/will Proton support WebAuth standard for 2FA?

Thanks guys you are doing awesome job!!!!

**Comment by wussler** [comment]
Hi @okonon, thank you for your report. 
We're fixing passkeys, they'll shortly be available for authentication too.

**Comment by mmso** [comment]
This should be available now :)
