### ISSUE TITLE
Auto-focus "Authenticate" button on "Two-factor authentication" page

### ISSUE THREAD

**Issue by julemand101** [ProtonMail/WebClients#295]
When using two-factor with security key, it would be nice if the button "Authenticate" would be automatic in focus so you can just click enter right away to start the authentication with the security key. If you want to use the keyboard right now, you need to click tab 4-5 times before you get focus on the "Authenticate" button.

For inspiration, look at GitHub where the "Use security key" button is focused right away after login which makes it quick to start the two factor authentication process just using the keyboard. :)

**Comment by nico3333fr** [comment]
Good idea, we sent a fix, it should be published soon ;)

**Comment by julemand101** [comment]
Verified today and seem to have been implemented and works as intended. Thanks! 👍

**Comment by nico3333fr** [comment]
Thanks a lot for suggesting <3
