### ISSUE TITLE
Why remove trailing slashes in link confirmation modal

### ISSUE THREAD

**Issue by tholam** [ProtonMail/WebClients#296]
> We are happy to answer your questions about the code or discuss technical ideas.

Please complete the following checklist (by adding [x]):

-   [x] I have searched open and closed issues for duplicates
-   [x] This isn't a feature request
-   [x] This is not a report about my app not working as expected

---

I noticed that the link confirmation modal removes trailing slashes on the web client and not ios.

https://github.com/ProtonMail/WebClients/blob/51742625834d3bd0d10fe0c7e76b8739a59c6b9f/packages/components/hooks/useLinkHandler.tsx#L141
https://github.com/ProtonMail/WebClients/blob/51742625834d3bd0d10fe0c7e76b8739a59c6b9f/packages/components/helpers/url.ts#L63

I was wondering why this change was made as it breaks some urls.  

For example southwest emails contain urls like this `https://t.iluv.southwest.com/r/?<query params>` but the link confirmation removes that trailing slash `https://t.iluv.southwest.com/r?<query params>` which breaks the routing.

**Comment by mmso** [comment]
Thanks for the report. Should be fixed now.
