### ISSUE TITLE
Infinite scroll not fetching more messages

### ISSUE THREAD

**Issue by JulienPalard** [ProtonMail/WebClients#30]
* Version 57.0.2987.98 built on Debian 9.0, running on Debian 9.0 (64-bit)
* Column mode
* Message mode
* Can you reproduce the problem each time? Yes
* Which url? `https://mail.protonmail.com/`

### What steps will reproduce the problem?

* 1) Log in to mail.protonmail.com
* 2) Look at the number of messages near a label or a folder in my case "python-ideas (431)", or "spam (999+).
* 3) Go to the given label or folder
* 4) In my case, the number of messages displayed is far less than the number of messages advertised, like, ~50.

### What is the expected result?

I expect the interface to lazily load as I scroll, an "infinite scroll", so I can find very old mails without having to use the search engine, just by scrolling.

### What happens instead?

No new mails are displayed, so I can see only about 50 emails, there should be more.

**Comment by emersion** [comment]
Note: for now, we use a pagination system. You can navigate between pages with the button in the top right corner.

**Comment by JulienPalard** [comment]
Waw, this button is far far away, I completly missed it, and I'm probably not alone.

So this issue is probably more like a "Pagination button are hard to find"?

**Comment by JulienPalard** [comment]
For the record, here's what I see:
![protonmail](https://cloud.githubusercontent.com/assets/239510/24455382/95c18a32-148f-11e7-88de-839f5b86e1d8.png)

The pages button (top right) are very far of the tread list, I suspect a lot of people won't find them, but I may be wrong.

**Comment by daylightbrightledlight** [comment]
I agree with @JulienPalard. I think the pagination button should be strategically located depending on the layout.

With the default "Column" layout, the pagination button should be aligned to the right of the column for easier access.

![95c18a32-148f-11e7-88de-839f5b86e1d8](https://user-images.githubusercontent.com/28210502/29151133-328ce7b4-7d4d-11e7-9866-6de4a9767988.png)

**Comment by JulienPalard** [comment]
I like the idea from @daylightbrightledlight, yet I'd probably prefer infinite scroll (if correctly implemented…).

**Comment by JulienPalard** [comment]
Hi @EpokK, thanks for jumping in.

This "wontfix" label mean that someone at Protonmail thinks that it is a good design choice to put those buttons far away? I'm no "UX guy", I only have my personal experience: when Protonmail switched from infinite scroll to "buttons far far away" I had hard [1] times to find them.

[1]: So hard I opened this issue thinking it was a bug.

**Comment by Hjiaky** [comment]
Infinite Scroll is needed.
At least the buttons schould be moved.

**Comment by JulienPalard** [comment]
I do not understand why this issue is closed.

**Comment by emersion** [comment]
This issue is closed because infinite scrolling is not used, pagination is used instead.

**Comment by JulienPalard** [comment]
Let's be pendantic and open a new one, if it's the subject of the issue that matter. https://github.com/ProtonMail/WebClient/issues/104.
