### ISSUE TITLE
Hunter.io indexing your proton.me domain

### ISSUE THREAD

**Issue by ghost** [ProtonMail/WebClients#300]
Hello!
Service hunter.io indexes proton.me domain  (screenshot 1), when the domain protonmail.com is excluded from the search because of that is a personal email creating service (screenshot 2).

Please contact the hunter.io team with a request to exclude your domains from the search as well. **They exclude all domains that are using to create personal addresses (but they need an official request).**

[Screenshot 1](https://user-images.githubusercontent.com/122489714/211920365-458e113c-c5a1-4b2d-81a4-7bbb7f5fae5e.jpeg)
[Screenshot 2](https://user-images.githubusercontent.com/122488962/211918247-5d8420d9-dcab-41be-b73e-1a4189fc2e3f.jpeg)

**Comment by bartbutler** [comment]
Thanks for the heads up--I've sent them an email.

**Comment by Deuchnord** [comment]
Just found this issue, it looks like my domain name-specific email address is in their list too. Do I need to contact them myself?

**Comment by bartbutler** [comment]
I don't know. I haven't received a response from them.

**Comment by AmrithVengalath** [comment]
I would like to mention it also indexes protonmail.ch domain ![Screenshot-1](https://user-images.githubusercontent.com/34616860/216434683-b0142251-5f89-4343-87dc-97620e75c19b.png)

**Comment by gglepori** [comment]
Giovanni here from Hunter - thanks for your report.

The domains have been added to our webmail list and emails will no longer be provided or collected for them: 
![image](https://user-images.githubusercontent.com/22502961/216619646-58754ee4-27fb-467a-a450-9ceb95bc09fa.png)

**Comment by bartbutler** [comment]
Hi @gglepori ,

Thanks for the reply. Can you please ensure that none of protonmail.ch, protonmail.com, pm.me, and proton.me? This is a complete list of our current user domains.

Thanks!

**Comment by ghost** [comment]
> Giovanni here from Hunter - thanks for your report.
> 
> The domains have been added to our webmail list and emails will no longer be provided or collected for them: ![image](https://user-images.githubusercontent.com/22502961/216619646-58754ee4-27fb-467a-a450-9ceb95bc09fa.png)

Hello @gglepori!
Thank you for your measures.

But there is some more domains that had not been removed from your search.

There is a service of mail aliases simplelogin.io, which generates a full e-mail address, which works, roughly speaking, as a bridge between the real address and the sender, thereby hiding the real e-mail recipient.

This service is also intended for personal use and publishing its addresses in your search results may entail serious risks to users' privacy and security.

It is also important to note that SimpleLogin is also owned by Proton.

[Proof one.](https://proton.me/blog/proton-and-simplelogin-join-forces) 
[Proof two.](https://simplelogin.io/blog/simplelogin-join-proton/)

**Here's a list of SimpleLogin domains that should also be excluded from your search:**

```
simplelogin.com
simplelogin.fr
aleeas.com
slmail.me
8shield.net
dralias.com
```

**_Please remove them from your search._**

[Here is a link](https://github.com/simple-login/app/issues/1528) to the original issue in the SimpleLogin repository. [And here is a link](https://github.com/simple-login/app/discussions/1529)  to their official discussion of the issue.

**Comment by gglepori** [comment]
Thanks for sharing this!

All the domains you reported have been successfully added to our webmail
domains list. We no longer provide emails for them.

Thanks again for taking the time to report this to us 🙏

Giovanni

**Comment by ghost** [comment]
> Thanks for sharing this! All the domains you reported have been successfully added to our webmail domains list. We no longer provide emails for them. Thanks again for taking the time to report this to us 🙏 Giovanni
> […](#)

Dear @gglepori, they have added new domain `slmails.com`. Can you, please, exclude it too?

Here is a proof:
![883013F0-DF96-4115-9B2A-0F7CE95CEB60](https://user-images.githubusercontent.com/126164488/220897163-c8536fab-4fc9-4b58-b92f-eaab70d66fa4.jpeg)

**Comment by ghost** [comment]
> > Thanks for sharing this! All the domains you reported have been successfully added to our webmail domains list. We no longer provide emails for them. Thanks again for taking the time to report this to us 🙏 Giovanni
> > […](#)
> 
> Dear @gglepori, they have added new domain `slmails.com`. Can you, please, exclude it too?
> 
> Here is a proof: ![883013F0-DF96-4115-9B2A-0F7CE95CEB60](https://user-images.githubusercontent.com/126164488/220897163-c8536fab-4fc9-4b58-b92f-eaab70d66fa4.jpeg)

Dear @gglepori,
Small update :)
They also added `silomails.com`

Please take measures!

Proof:
![7E2B6BC9-4B94-4C9D-A0CC-F53772402993](https://user-images.githubusercontent.com/126249068/221165565-fea82c37-20b4-44e3-b580-67b1e4ee4b30.jpeg)

**Comment by gglepori** [comment]
@ghost

> > > Thanks for sharing this! All the domains you reported have been successfully added to our webmail domains list. We no longer provide emails for them. Thanks again for taking the time to report this to us 🙏 Giovanni
> > > […](#)
> > 
> > 
> > Dear @gglepori, they have added new domain `slmails.com`. Can you, please, exclude it too?
> > Here is a proof: ![883013F0-DF96-4115-9B2A-0F7CE95CEB60](https://user-images.githubusercontent.com/126164488/220897163-c8536fab-4fc9-4b58-b92f-eaab70d66fa4.jpeg)
> 
> Dear @gglepori, Small update :) They also added `silomails.com`
> 
> Please take measures!
> 
> Proof: ![7E2B6BC9-4B94-4C9D-A0CC-F53772402993](https://user-images.githubusercontent.com/126249068/221165565-fea82c37-20b4-44e3-b580-67b1e4ee4b30.jpeg)

Done, we've removed slmails and silomails. Thanks again for the report.

**Comment by ghost** [comment]
Thank you for your cooperation:)

**Comment by ghost** [comment]
Dear @gglepori they launched a Proton Pass and added next domains:

@passinbox.com
@passfwd.com

Please remove them too :)

Proof:
![IMG_8126](https://github.com/ProtonMail/WebClients/assets/138008095/7398bb02-5ff0-4869-a232-bdcd2d7d29e6)

**Comment by AmrithVengalath** [comment]
I'm wondering why can't proton use existing domains like apple use(hide my email - something@icloud.com, something@privaterelay.apple.com)

Is there actually any benefit? 

![image](https://github.com/ProtonMail/WebClients/assets/34616860/c1f954b8-1cd5-4a30-86b3-26391f4d6325)

**Comment by bartbutler** [comment]
Risk reduction. Nobody is going to block signups for icloud.com, they are too big. We are not "too big to block" so having multiple domains A) protects the non-alias domains B) gives users more options in case sites decide to block domains.

But I agree, it would be better to be able to use alias.proton.me or the like.

**Comment by gglepori** [comment]
Thanks for the report. We've added them to our webmail list.

**Comment by ghost** [comment]
Dear @gglepori,
Sorry for bothering you again but they had added new two domains again.

Here is the proof:
![IMG_8612](https://github.com/ProtonMail/WebClients/assets/140086413/6c335f07-a942-45f5-bdea-1ee059111145)

Please exclude following domains:
@passmail.com
@passmail.net

**Comment by gglepori** [comment]
All set 👍 Thanks for sharing the domains.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/ProtonMail/WebClients/issues/300#issuecomment-1651673861

This should be closed.
