### ISSUE TITLE
Multiple `nm-openvpn-auth` processes in Ubuntu flagged as Zombie

### ISSUE THREAD

**Issue by mcmxcdev** [ProtonMail/WebClients#310]
> We are happy to answer your questions about the code or discuss technical ideas.

Please complete the following checklist (by adding [x]):

-   [x] I have searched open and closed issues for duplicates
-   [x] This isn't a feature request
-   [x] This is not a report about my app not working as expected

---

I am using the Proton VPN .deb installation and it seems that there are always multiple zombie processes popping up that don't get cleaned up:

![image](https://user-images.githubusercontent.com/16797721/224361154-aa5f7408-8c8e-4a7f-95ce-6c4030bb3862.png)

**Comment by mmso** [comment]
Could you open your issue here instead? https://github.com/ProtonVPN/linux-app

Closing this because it's the web clients.

**Comment by mcmxcdev** [comment]
Opened an issue in that repository instead: https://github.com/ProtonVPN/linux-app/issues/104
