### ISSUE TITLE
Tags publishing stopped again

### ISSUE THREAD

**Issue by vladimiry** [ProtonMail/WebClients#317]
No updates at https://github.com/ProtonMail/WebClients/tags.

For example, currenlty deployed mail app version is 5.0.19.3 https://mail.proton.me/assets/version.json, but the most recent published tag is proton-mail@5.0.19.2.

**Comment by mmso** [comment]
Thanks we are currently fixing this. It was due to the github ssh keys being cycled :) https://github.blog/2023-03-23-we-updated-our-rsa-ssh-host-key/

**Comment by vladimiry** [comment]
Closing as fixed. Thanks.
