### ISSUE TITLE
Please enable saving translations in XLIFF format

### ISSUE THREAD

**Issue by xet7** [ProtonMail/WebClients#320]
Hi,
I did translate remaining translation strings to Finnish today.

Please enable Export in XLIFF format, it is grayed out:

![xliff](https://user-images.githubusercontent.com/15545/234684709-51d27f93-3895-46a0-a796-5d882d0da1b5.png)

I was able to build ProtonMail from newest Git commits of this repo using these steps https://github.com/wekan/wekan/wiki/ProtonMail , start it locally, login, and use older translations I had, but I can not download newest translations to test do they show correctly in ProtonMail menus, because downloading in XLIFF format is not enabled:

![proton-old](https://user-images.githubusercontent.com/15545/234685206-672fdd0f-de92-4cfd-a38c-1582ffbe975b.png)

**Comment by dhoko** [comment]
@xet7 :wave: it was disabled yesterday for a few tests, the option should be back now

**Comment by xet7** [comment]
Thanks, now option is back !
