### ISSUE TITLE
Cannot use hotkeys like 'a' for Archive while message is being viewed

### ISSUE THREAD

**Issue by camelpunch** [ProtonMail/WebClients#33]
* Which browser? Chrome
* Which OS? Mac OS
* Which layout mode? Column mode
* Which threading mode? Conversation mode
* Can you reproduce the problem each time? Yes
* Which url? `/inbox/somereallylongbase64likestring`

### What steps will reproduce the problem?

* 1) Go to inbox that has mail
* 2) Hit `enter` to read a mail
* 3) Try to archive with `a`

### What is the expected result?

Message is archived

### What happens instead?

Nothing. I have to hit `esc` before `a`. Even `x` to select doesn't let me archive after I've started reading a mail.

### Please provide any additional information below. Attach a screenshot if possible.

If, instead of hitting `enter` to read the message, I click the message to read it, I can use `a` to archive.

**Comment by dhoko** [comment]
Hey,

Can you reproduce the problem with the latest version ?

**Comment by camelpunch** [comment]
I'm afraid not: I moved away from ProtonMail since filing this issue.
