### ISSUE TITLE
Translations: Proton VPN EasySwitch not translateable, please add

### ISSUE THREAD

**Issue by xet7** [ProtonMail/WebClients#330]
> We are happy to answer your questions about the code or discuss technical ideas.

Please complete the following checklist (by adding [x]):

-   [X] I have searched open and closed issues for duplicates
-   [X] This isn't a feature request
-   [X] This is not a report about my app not working as expected

---
Hi,
Proton VPN EasySwitch not translateable, please add translation strings. Thanks!

![proton-vpn-easy-switch-not-translated](https://github.com/ProtonMail/WebClients/assets/15545/59a37c31-0f06-4582-a049-b8abe996a17b)

**Comment by olavinto** [comment]
Either you were too quick to report this or they already reacted to it because the strings were just added:
https://proton.crowdin.com/translate/f35cb82aa1f51792b92a8b0ee4f239c1/4178/en-fi#940703
https://proton.crowdin.com/translate/f35cb82aa1f51792b92a8b0ee4f239c1/4178/en-fi#940705

**Comment by xet7** [comment]
@olavinto 

Yes, I'm currently translating those newly added strings.

**Comment by dhoko** [comment]
Our queue sending strings to crowdin was stuck :/ 
This string might have been waiting inside for 2 days :facepalm:
