### ISSUE TITLE
Translations: ProtonVPN OpenVPN not translateable

### ISSUE THREAD

**Issue by xet7** [ProtonMail/WebClients#331]
> We are happy to answer your questions about the code or discuss technical ideas.

Please complete the following checklist (by adding [x]):

-   [X] I have searched open and closed issues for duplicates
-   [X] This isn't a feature request
-   [X] This is not a report about my app not working as expected

---
Hi,
this text is not translateable, please add. Thanks!

![proton-vpn-openvpn-not-translated](https://github.com/ProtonMail/WebClients/assets/15545/fd49219d-85b4-4a95-8b7c-eb566a44e293)

**Comment by olavinto** [comment]
I believe that it should be this string but it's not included for some reason although it has been translated (not approved though):
https://proton.crowdin.com/proofread/f35cb82aa1f51792b92a8b0ee4f239c1/4178/en-fi#569538

**Comment by xet7** [comment]
@olavinto 

Currently Finnish is 100% translated, but not all approved.

**Comment by olavinto** [comment]
Yeah, I have proofread a lot of it during the past week or two and it's currently a bit over 40 % is done. I also can't proofread everything myself, including many changes that I have made while proofreading. But the translations seem to include those strings too so this should also be there.

**Comment by mmso** [comment]
Deploying the fix for this tomorrow, thanks @xet7
