### ISSUE TITLE
ProtonPass: create alias possible only with one of my several emails

### ISSUE THREAD

**Issue by dimitri-bourreau** [ProtonMail/WebClients#334]
-   [x] I have searched open and closed issues for duplicates
-   [x] This isn't a feature request
-   [x] This is not a report about my app not working as expected

---

# I can't select an email for a new alias

Using the ProtonPass Firefox extension, I want to create an alias.

In the `Forwards to` section, I can not select the email.

One email is selected, which was the default email address from my ProtonMail account.

I don't want aliases to redirect to this professional email, thus I've updated my default email from my ProtonMail account.

A week passed, I still only can create aliases for this previously default email, which I don't want to use.

# Questions

- Is this behaviour as expected?
- Did I miss something?

# Tech details

- I have a Business Plan
- I have 11 email addresses registered in my ProtonMail account
- I use Firefox 115.0.2 (updated) on Mac OS 13.4.1
- The same issue appear on my ProtonPass app for my iPhone

**Comment by qudix** [comment]
Proton Pass uses SimpleLogin to generate the aliases, which means you have to add additional email addresses in the MailBoxes section on the SimpleLogin dashboard. After that they should show up in the `Forwards To` section. At least they did on the mobile app. I'm unsure how to refresh the browser extension to detect the change immediately besides restarting the browser.

**Comment by roschlau** [comment]
@Qudix Oh wow, that is obscure. This solution works perfectly, but is absolutely impossible to find on your own right now. As long as there no way to configure this stuff from Proton Pass, there needs to at least be a hint in the UI to go to SimpleLogin to configure additional addresses.

**Comment by dimitri-bourreau** [comment]
Thanks @Qudix , I'm not sure how to do this via SimpleLogin, anyway maybe we found a nice improvement to ProtonPass?

As @roschlau says, the UI may guide a little more on that procedure. 👍

**Comment by roschlau** [comment]
@Qudix You need to use the "Login via Proton" button to log in to SimpleLogin, and then create a Mailbox for any email address you want to be able to choose in Proton Pass.

**Comment by dimitri-bourreau** [comment]
Considering a week has passed, I'm closing this issue regarding the fact a working solution has been proposed.

Though, I believe reflecting this discussion on the UI would have been a good idea!

Anyway, have a good code everyone. ✌️
