### ISSUE TITLE
ProtonPass: distinguish ambiguous letters/digits

### ISSUE THREAD

**Issue by jm33-m0** [ProtonMail/WebClients#338]
-   [x] I have searched open and closed issues for duplicates
-   [x] This isn't a feature request
-   [x] This is not a report about my app not working as expected

---

![image](https://github.com/ProtonMail/WebClients/assets/10167884/918732aa-9f8e-4574-868e-a0b679d9fa49)

In the above screenshot my password is `1IlO0`, but you can hardly tell by just looking at it, I have to copy and paste it in Vim to know which is `I` and which is `l`.

How it should be done:

![image](https://github.com/ProtonMail/WebClients/assets/10167884/98526494-abbe-42ea-95df-cc418abdfbd9)

**Comment by D-Bao** [comment]
Thanks for the feedback, we implemented a monospace font for the password field (in 18a8186158c9c5325874bd545db9326c3e334c91) and it will be released in the next version.

**Comment by jm33-m0** [comment]
Thanks, please make it happen in mobiles apps as well.
