### ISSUE TITLE
Is there a repo for iPad ProtonDrive code?

### ISSUE THREAD

**Issue by dimitri-bourreau** [ProtonMail/WebClients#339]
## This is a question, not an issue report

-   [x] I have searched open and closed issues for duplicates
-   [x] This isn't a feature request
-   [x] This is not a report about my app not working as expected

## Question

I've met important issues concerning the iPad ProtonDrive app.

**Is there a public repo for this app?**

## Optional details

Very slow at booting, freezing when booting is done.

The app on my iPhone works great. 

I have about ~130Go used on my ProtonDrive. This happend since I've uploaded about 50Go of data (`.heic` pictures).

I wanted to share this issue with its details and video capture, but didn't find any dedicated repo. 

Thanks!

**Comment by dhoko** [comment]
@dimitri-bourreau 👋 hello, yep it's available here ->  https://github.com/ProtonDriveApps/ios-drive

**Comment by dimitri-bourreau** [comment]
@dhoko Thanks! 🙏

We can't create issues there, do you know if there is a place dedicated to report issues or do this project simply do not accept outsiders' issues?

Anyway I close this issue. ✌️
