### ISSUE TITLE
<noscript> Does not show when JavaScript is disabled

### ISSUE THREAD

**Issue by amdelamar** [ProtonMail/WebClients#34]
* Which browser? Firefox v52 (32bit)
* Which OS? Windows 10
* Which layout mode? _Not Applicable_
* Which threading mode? _Not Applicable_
* Can you reproduce the problem each time? Yes
* Which url? https://mail.protonmail.com/

### What steps will reproduce the problem?

* 1) Disable JavaScript
* 2) Open https://mail.protonmail.com/

### What is the expected result?

`<noscript>` tag should appear.

### What happens instead?

`<noscript>` tag is covered up and not visible.

### Please provide any additional information below. Attach a screenshot if possible.

```html
<!-- No Script message -->
<div id="loading_pm">
    <noscript style="padding: 2rem; display:block; text-align: center; color: #fff">ProtonMail requires Javascript. Enable Javascript and reload this page to continue.</noscript>
</div>
```

![ProtonMail without JavaScript Enabled](https://i.imgur.com/ZhE8BF8l.jpg)

**Comment by amdelamar** [comment]
✅  This can be fixed by adding positioning to the <noscript> tag. (`position: relative;`)

So the code would be:

```html
<!-- No Script message -->
<div id="loading_pm">
    <noscript style="padding: 2rem; display:block; text-align: center; color: #fff; position: relative;">ProtonMail requires Javascript. Enable Javascript and reload this page to continue.</noscript>
</div>
```

**Comment by buildog** [comment]
![noscript-](https://user-images.githubusercontent.com/18439883/27656812-ba55830a-5c4a-11e7-9850-ec9c6efb4fc2.png)

Done. Thanks for the report @amdelamar!

**Comment by amdelamar** [comment]
Great work 👍
