### ISSUE TITLE
Prospect.io and ninjaoutreach.com and findemails.com and voilanorbert.com and Snov.io and getprospect.com indexing your domains!

### ISSUE THREAD

**Issue by Ha-X-0R** [ProtonMail/WebClients#346]
Hello!

Prospect.io and voilanorbert.com and getprospect.com and snov.io and ninjaoutreach.com and findemails.com indexing your domains!

Please contact their teams with a request to exclude your domains from the search as well. They exclude all domains that are using to create personal addresses (but they need an official request).

Also they are indexing ALL SimpleLogin and ProtonPass domains. Here is the list of indexed domains:

```
protonmail.ch
proton.me
pm.me
simplelogin.com
silomails.com
slmails.com
simplelogin.fr
aleeas.com
slmail.me
8shield.net
dralias.com
passinbox.com
passfwd.com
passmail.com
passmail.net
simplelogin.co
simplelogin.io
```

Please contact them to resolve this as soon as possible!

@bartbutler can you please take a look?

**Comment by bartbutler** [comment]
I've done what I can here. Wow are there a lot of these "services".
