### ISSUE TITLE
https://maildump.co/domain-search indexing your domains

### ISSUE THREAD

**Issue by L4B0R4NT** [ProtonMail/WebClients#347]
Hello!

I am from Reddit post.

https://maildump.co/domain-search indexing your domains

![IMG_0111](https://github.com/ProtonMail/WebClients/assets/144471726/5db93c12-5d6b-4ab3-a31d-de8cd6f1bf8e)

Here is the list of indexed domains:

```
protonmail.ch
proton.me
pm.me
simplelogin.com
silomails.com
slmails.com
simplelogin.fr
aleeas.com
slmail.me
8shield.net
dralias.com
passinbox.com
passfwd.com
passmail.com
passmail.net
simplelogin.co
simplelogin.io
```

@bartbutler  in post said that I have to ping you

**Comment by Cyyfucivuvj** [comment]
@bartbutler protonmail.com is indexed too

![IMG_0135](https://github.com/ProtonMail/WebClients/assets/144557868/5f3234cc-9e42-46d6-a57c-81206ae79f76)

But gmail.com excluded:
![IMG_0136](https://github.com/ProtonMail/WebClients/assets/144557868/ce43153a-40a2-4e8a-aa04-4d17da9bd0e7)

**Comment by bartbutler** [comment]
Submitted request.
