### ISSUE TITLE
Consider adding an opaque background to the favicon.

### ISSUE THREAD

**Issue by audreytoskin** [ProtonMail/WebClients#35]
The favicon for both the main website (protonmail.com) and the web mail client (mail.protonmail.com) are currently a dark color on a transparent background. This makes it hard to see the icon when the browser is using a dark UI theme. If the favicon were edited to use an opaque (or even translucent) background color, it would assure sufficient contrast to be visible on all web browsers.

I see this same issue when testing in both Firefox Beta 54.0b2 and Google Chrome Beta 58.0.3029.81, on Fedora 25 Workstation x86_64.

![screenshot from 2017-04-27 16-57-29](https://cloud.githubusercontent.com/assets/3881885/25509011/a8fa0826-2b6a-11e7-9729-231cfcecbced.png)

![screenshot from 2017-04-27 16-30-59](https://cloud.githubusercontent.com/assets/3881885/25508669/93d54746-2b68-11e7-9eec-f0b100be1d6a.png)

**Comment by dlukes** [comment]
+1 on this, the icon is very nice, it would be great if it stood out more on dark backgrounds :)

**Comment by dhoko** [comment]
it's live ;)  
![screenshot from 2017-11-08 18-28-27](https://user-images.githubusercontent.com/713283/32563863-a0f3d9fe-c4b2-11e7-876b-e4635f7226bd.png)
