### ISSUE TITLE
Full window view

### ISSUE THREAD

**Issue by marke525** [ProtonMail/WebClients#350]
I have installed the Firefox plugin and it works well.  However, it will only open as a small window in the corner of the browser.  I have many passwords.  It would be useful if I could open ProtonPass to be a full window.  I have not been able to determine how to do this.  Is this possible?

**Comment by D-Bao** [comment]
Thanks for your feedback, that feature is in our roadmap so stay tuned!

**Comment by anasouardini** [comment]
Any chance I could be part of it? I'm interested in contributing to this feature.

**Comment by D-Bao** [comment]
That would have been very nice but this feature was implemented in https://github.com/ProtonMail/WebClients/commit/fd3bbfc274f9cbf918a7511485b42431499dd5e4.  
The ability to open Proton Pass in a separate window that can be resized to full size is now available on Chromium browsers. It will be released in the next version for Firefox.

**Comment by marke525** [comment]
Thanks for letting me know.

I only use Firefox, so that explains why I haven't seen it yet.

Regards,

Mark

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------
