### ISSUE TITLE
Can't connect to backend in dev mode

### ISSUE THREAD

**Issue by karolchmist** [ProtonMail/WebClients#36]
### What steps will reproduce the problem?

* 1) Run npm start
* 2) open localhost:8080
* 3) log in

### What is the expected result?
Be able to log in

### What happens instead?
Error message : A new version of ProtonMail is available. Please refresh this page and then logout and log back in to automatically update.

### Please provide any additional information below. Attach a screenshot if possible.
I'm on the master branch and up-to-date. I guess the client is behind the api version. I would like to contribute to PM, but I'm unable...

**Comment by shreeshbhat** [comment]
Same issue happening to me too. Would love to contribute to this project. 
@EpokK : Kindly let us know the steps to login successfully.

**Comment by EpokK** [comment]
It should work now.
