### ISSUE TITLE
Proton blocked in blacklist

### ISSUE THREAD

**Issue by ghost** [ProtonMail/WebClients#365]
Hi!

On this https://github.com/disposable/disposable/blob/master/greylist.txt you got blocked

This is really popular filter, so please, take measures!

@mmso, @bartbutler, @Twikito

**Comment by ghost** [comment]
@mmso, @bartbutler, @Twikito, @mmso, @HeadFox, @StraightOuttaCrompton, @flavienbonvin and other developers please take action! 

### All SimpleLogin, Proton and Proton Pass domains banned!

**Comment by bartbutler** [comment]
It's "allow anonymous signup", which I guess is true, so I'm not sure there's much to be done here.
