### ISSUE TITLE
Add LibreJS Support

### ISSUE THREAD

**Issue by agarrharr** [ProtonMail/WebClients#37]
It would be nice if you could add the licenses to the JavaScript so that it can run with the [LibreJS Firefox browser extension](https://www.gnu.org/software/librejs/) enabled. Here is more information about how to do this: https://www.gnu.org/software/librejs/free-your-javascript.html.

* Which browser? Firefox

### What steps will reproduce the problem?

* 1) Install LibreJs
* 2) Navigate to https://protonmail.com/signup
* 3) Notice the message "Javascript is required to sign up. Please enable Javascript and reload this page."

### What is the expected result?

The page should work normally and show a form to sign up.

### What happens instead?

The JavaScript gets blocked because LibreJs cannot find any free software licenses for the JavaScript.

**Comment by brochard** [comment]
How is this closed as "completed" ? It doesn't appear to be implemented.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/ProtonMail/WebClients/issues/37#event-5141905374

@brochard, there certainly should be a commit or PR attached. Perhaps it was meant to be closed as unplanned?
