### ISSUE TITLE
how to delete drive volume

### ISSUE THREAD

**Issue by olumolu** [ProtonMail/WebClients#383]
> We are happy to answer your questions about the code or discuss technical ideas.

Please complete the following checklist (by adding [x]):

-   [x] I have searched open and closed issues for duplicates
-   [x] This isn't a feature request
-   [x] This is not a report about my app not working as expected

---
I just wanted to small the first letter of my new email id but when i was doing it. It is having an error.
How can i delete my drive volume can anyone help.
![Screenshot_20240315-230048~3](https://github.com/ProtonMail/WebClients/assets/162728301/c33d84ba-9cfa-4078-9c07-5df501017007)
![Screenshot_20240315-230048~2](https://github.com/ProtonMail/WebClients/assets/162728301/f8870869-a158-4ece-9a03-56512c15e085)

**Comment by Willie30F** [comment]
What's the solution to this please? 🥲

**Comment by olumolu** [comment]
Send a mail to proton mension that you want to delete your drive volume they will ask you are you sure if you say yes they will do it in 3-5days in my case it was quick with in 1day.
