### ISSUE TITLE
Question: How setup my instance    

### ISSUE THREAD

**Issue by nyancat18** [ProtonMail/WebClients#39]
How can i setup my protonmail instance?

**Comment by Super-Baleine** [comment]
hey,
i guess everything you need is on the README.md file.

if you wanna install a pm server that's just impossible.

**Comment by nyancat18** [comment]
@Super-Baleine    i've wanted to install a protonmail server   at tor

for get a sadsaf@safddsafdsaf.onion  (this ist the real url)  

at my home server,   lol :D

**Comment by Super-Baleine** [comment]
ya cant, their backend _**is unfortunately not**_ open source :/

**Comment by nyancat18** [comment]
doh 


the lesser bad its
a grsec-server   
with roundcube

**Comment by streaps** [comment]
https://github.com/emersion/neutron

**Comment by EvanCarroll** [comment]
This would be so much less crappy if ProtonMail would just own up to having the back-end close source, rather than trying to bury all discussions on it. Put it in the docs at the top.

> The back-end is not open source, only the web-client for our service. You can not self-host or run this in isolation.
