### ISSUE TITLE
Selectable email address label

### ISSUE THREAD

**Issue by raphaelbastide** [ProtonMail/WebClients#41]
In the _compose_ email panel, it would be really helpful to let the user select, copy, delete easily the email address in the TO CC BCC fields just like [that](http://sliptree.github.io/bootstrap-tokenfield/). 

* Which browser? Chrome / Firefox
* Which OS? Linux
* Which layout mode? Column mode
* Which threading mode? Conversation mode / Message mode
* Can you reproduce the problem each time? Yes 

### What steps will reproduce the problem?

* 1) Compose a message, add one or many recipient
* 2) Try to copy recipient’s email in the TO field, both with the cursor and keyboard only.

### What is the expected result?

Like some web mail clients, a double click on the recipient’s name + email label could turn it into raw text, just like [this script](http://sliptree.github.io/bootstrap-tokenfield/) behave.

### What happens instead?

It is really painful to select the address label’s content with the mouse’s cursor or the keyboard (shift + ⬅️ or shift + ➡️ ). It is consequently really difficult to copy an already written address. Double clicking on an address label does not select the address, and with my configuration, it loses the selection right after the selection, unlike in any text field.

**Comment by dhoko** [comment]
The patch is live :)
You can select the  recipient’s name + email without losing the focus.

**Comment by raphaelbastide** [comment]
@dhoko I can’t see the result, or it doesn’t solve the issue I opened.

**Comment by dhoko** [comment]
![output](https://user-images.githubusercontent.com/713283/29015595-e329f73e-7b4e-11e7-98c6-349257dc2d5a.gif)
I don't understand,  I created this gif on live.

**Comment by raphaelbastide** [comment]
Thank you for the gif, the focus is kept with the mouse’s cursor indeed. But those fields are still not accessible with the keyboard, that is a major part of this issue. This [demo](http://sliptree.github.io/bootstrap-tokenfield/) sums up what should be done -in my opinion- to make the fields keyboard accessible. What do you think?

**Comment by dhoko** [comment]
ok, I will try to add it soon. Thx for your feedback.
