### ISSUE TITLE
See the ProtonMail email address easily

### ISSUE THREAD

**Issue by thomas-kuntz** [ProtonMail/WebClients#42]
I was looking for the exact email address of my ProtonMail account, and the only way I found to get it is to click on the user icon in the top tool-bar of the web interface (on desktop Linux, with Firefox 54), but unfortunately the email address is truncated...

I think it would be better to make the thing that appears when we click on our user name in the tool-bar bigger so that the email address is not truncated. Or at least there should be an option to expand it if the address happens to be *really* too long (mine is quite short but was truncated).

![capture du 2017-06-20 12-43-49](https://user-images.githubusercontent.com/16361470/27329557-533a5ce4-55b6-11e7-8646-ecfca6280f74.png)

So, make this bigger so that we see the entire email address:
![capture du 2017-06-20 12-44-17](https://user-images.githubusercontent.com/16361470/27329576-67149e00-55b6-11e7-9c41-a017c27c391d.png)

And if it's **really** too long, truncate it but put something like this to expand it if we want to:
![capture du 2017-06-20 12-44-52](https://user-images.githubusercontent.com/16361470/27329626-939bc124-55b6-11e7-85b5-20316598325f.png)

**Comment by szepeviktor** [comment]
You could add the ellipsis by CSS:after and double-clicking the address will select it all.

**Comment by Rafficer** [comment]
This won't solve the problem itself, but you could just open the composer. There it shows the full email address.

**Comment by thomas-kuntz** [comment]
Right, I didn't think of it...
