### ISSUE TITLE
npm install exits on node-sass installation

### ISSUE THREAD

**Issue by streaps** [ProtonMail/WebClients#43]
I tried to install and run the WebClient, but it seems some font-awesome file is missing. Is this a bug or do I need to install the font-awesome file manually? 

```
~/WebClient# npm start

> protonmail-web@3.9.1 start /root/WebClient
> grunt watch --api=dev

Running "notify_hooks" task

Running "ngconstant:dev" (ngconstant) task
Creating module proton.config at src/app/config.js...OK

Running "clean:build" (clean) task
>> 1 path cleaned.

Running "html2js:app" (html2js) task
Successfully converted 191 html templates to js.

Running "sass:build" (sass) task
>> Error: File to import not found or unreadable: ../../vendor/components-font-awesome/scss/font-awesome
>>        Parent style sheet: /root/WebClient/src/sass/_icons.scss
>>         on line 1 of src/sass/_icons.scss
>> >> @import "../../vendor/components-font-awesome/scss/font-awesome";
>>    ^
Warning:  Use --force to continue.

Aborted due to warnings.

npm ERR! Linux 4.4.0-83-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v6.11.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! protonmail-web@3.9.1 start: `grunt watch --api=dev`
npm ERR! Exit status 6

```

**Comment by streaps** [comment]
`node_modules/.bin/bower install` solved it.

~~Maybe this could be mentioned in README.md under Basic Installation.~~

**Comment by streaps** [comment]
`npm install` doesn't install node-sass correctly and stops there. What works is:
```
npm install
npm install node-sass
npm install
npm start
```

Any idea why node-sass doesn't get installed with `npm install`, but does with `npm install node-sass`?

**Comment by dhoko** [comment]
Hey, 

idk, I cloned WebClient a few minutes ago and did a `$ npm i`. 
No errors after the `$ npm start`  ¯\_(ツ)_/¯

- `$ node -v`: _v7.0.0_
- `$ npm -v`: _v3.10.8_

Did you try to clean your cache ?

Edit idem with node _v6.3.1_

**Comment by streaps** [comment]
Thanks dhoko. I still have no idea why this is happening, but it's good to know that it seems to be specific to my build environment. More trial end error...

**Comment by dhoko** [comment]
Did you try to clear the cache from npm and node_modules before `$ npm i` ?

**Comment by streaps** [comment]
I installed it in a fresh lxc container (Ubuntu 17.04).

**Comment by streaps** [comment]
It works for me on a normal Ubuntu setup. I wonder if the problem was related to the LXC container. I assume it is a bug in LXC and/or node-sass.
