### ISSUE TITLE
domain name configuration dialog box is too small

### ISSUE THREAD

**Issue by jumblerg** [ProtonMail/WebClients#46]
important config settings needlessly wrap to additional lines and disappear under the side of the box.

![screen shot 2017-07-28 at 20 38 34](https://user-images.githubusercontent.com/169224/28740622-247aa4bc-73d5-11e7-97e9-6745f4231e5b.png)

![screen shot 2017-07-28 at 20 39 12](https://user-images.githubusercontent.com/169224/28740616-185209aa-73d5-11e7-9fb7-2382ca2e4a7a.png)

**Comment by nico3333fr** [comment]
Hi there,

did you consider using `overflow-wrap: break-word;` only on the cell that is containing this too long text?
(it might be combined with `word-wrap: break-word` depending on the compatibility you need)

Kind regards,
Nicolas

**Comment by EpokK** [comment]
This is fixed.
