### ISSUE TITLE
Source code seems hardcoded towards existing online service

### ISSUE THREAD

**Issue by ozra** [ProtonMail/WebClients#5]
I'm ditching gmail and need a webmail service on my VPS. I just stumbled upon protonmail today, while looking for candidates to evaluate. Naturally I'd like to minimize the time spent with each solution to sort out the good and the bad.

Problem: When trying the quick try-out way: npm install && npm start, it's possible to create accounts from the app, but they seem to work towards the official online service of the company behind the product.

I thought I'd ask quickly before spending time on reviewing the source code, since I have a long list of candidates to sift through.

Is this only superficial (in the UI, and the "user name taken" lookup)? Or does it actually create an account on the existing service rather than on my own box?

**Comment by bartbutler** [comment]
This is the web client for the ProtonMail email service. Accounts are hosted on ProtonMail servers. It is not a standalone mail service.

**Comment by ozra** [comment]
Sorry for taking up the time on it. Is there a special repo for a decentralized version (configurable-for-my-server) on some downstream-fork? Or how can one best leverage the code and contribute back upstream?

**Comment by emersion** [comment]
See https://github.com/emersion/neutron

**Comment by ozra** [comment]
@emersion : "Neutron" - haha, of course B-) Does it track upstream (updates) and contribute back, or is it a "loose fork"?

**Comment by bartbutler** [comment]
It's a side project/loose fork and is not supported in any way. The ProtonMail Web Client is designed for use with the ProtonMail API, not for self-hosted solutions. Sorry.

**Comment by emersion** [comment]
@ozra It tracks upstream changes, as it pulls the official ProtonMail client. As @bartbutler said, it is a side project and it is not supported nor affiliated to ProtonMail. If you have further questions, please ask them on the repo instead of in this thread. ;-)

**Comment by ozra** [comment]
Thanks for clearing up - I realize it's unsupported - just wanted to know that it helps back to ProtonMail with fixes and what not.
Over and out! :-)
