### ISSUE TITLE
[Suggestion] Block embedded images in spam folder by default

### ISSUE THREAD

**Issue by amdelamar** [ProtonMail/WebClients#50]
### What steps will reproduce the problem?

* 1) Receive an email in the spam folder.
* 2) Open it to read.
* 3) Email auto-loads embedded images. (If enabled.)

### What is the expected result?

Emails in spam folder should ask to show images. Even if you embedded images are enabled for your inbox.

Images sometimes secretively used to track "read receipts" or if the recipient has opened the email. Thus, betraying your privacy. **If an email does not make it past the spam filter, then it should not be allowed to auto-load images**. Unless the user allows it temporarily. (Show the option to enable images for this single email.)

To get around this, I have to change ProtonMail settings to check whats in my spam folder. `Settings > Account > Email Content`. And then turn it back on after I'm done. And that's annoying.

### What happens instead?

Opening a spam email in spam folder should ask to display images. (Even if you enabled them for all emails like  your inbox). This is because I may not trust emails in my spam folder right away.

**Comment by EpokK** [comment]
That doesn't make sense.

**Comment by MasterInQuestion** [comment]
Description that makes sense:
    For Spam emails, automatic image loading shall be unconditionally disabled.
    For probably slightly more protection. (not necessarily really)

    The change is unlikely to impact user experience:
    Those expect to really read: the email wouldn't stay in Spam.
    Those who wouldn't read: not loading the images probably would be better.
    (less distraction, resource consumption)
