### ISSUE TITLE
Possibility of packing web-app as electron desktop mail client

### ISSUE THREAD

**Issue by Rafi993** [ProtonMail/WebClients#51]
* Which browser? 
* Which OS? Windows / Mac OS / Linux
* Which layout mode? Column mode / Row mode
* Which threading mode? Conversation mode
* Can you reproduce the problem each time? Yes
* Which url?

### What is the expected result?
Packing the web-app as desktop mail client

**Comment by kontrollanten** [comment]
I'm a contributor to a community driven (and unofficial) project which does exactly this, https://github.com/protonmail-desktop/application
