### ISSUE TITLE
feat/split branch?

### ISSUE THREAD

**Issue by lacivert** [ProtonMail/WebClients#52]
* Which browser (+ version) ? Chrome / Firefox / Safari / Opera
* Which OS (+ version)? Mac OS 
* Which layout mode? Column mode / Row mode
* Which threading mode? Conversation mode / Message mode
* Can you reproduce the problem each time? Yes / No
* Which url?

### What steps will reproduce the problem?

* 1) npm install

### What is the expected result?
installation by NPM

### What happens instead?
Gives error:
> npm ERR! code 1
> npm ERR! Command failed: /usr/bin/git checkout feat/split
> npm ERR! error: pathspec 'feat/split' did not match any file(s) known to git.

**Comment by kontrollanten** [comment]
The feat/split branch has been merged into master, so you should be able to just remove `#feat/split` from line 65 in package.json and then run `npm install` again.

**Comment by dhoko** [comment]
The new version contains the patch inside the package.json :)
