### ISSUE TITLE
Compose message UX issue

### ISSUE THREAD

**Issue by kskarthik** [ProtonMail/WebClients#53]
* Firefox / chrome
* Android
* Column mode / Row mode
* Compose Message mode
* Can you reproduce the problem each time? Yes

### What steps will reproduce the problem?

While composing a message, The below menu bar occupies the message area. This makes composing message a hassle. 

### What is the expected result?

The bottom menu should not cover the message area. 

### Screenshot

[![2017_10_16_11_38_46.png](https://s1.postimg.org/5cpywu7ar3/2017_10_16_11_38_46.png)](https://postimg.org/image/83z14wtesr/)

**Comment by dhoko** [comment]
Hey,

We deployed a fix a few days ago cf:

![screenshot_20171211-174419](https://user-images.githubusercontent.com/713283/33842526-0e612cc4-de9b-11e7-8ae9-3561a1c8a181.png)

is it ok on your device too ?

**Comment by kskarthik** [comment]
Yes, Fixed!
