### ISSUE TITLE
Conversations grouped by subject line only

### ISSUE THREAD

**Issue by wskinner** [ProtonMail/WebClients#54]
* Which browser (+ version) ? Chrome  61.0.3163.100
* Which OS (+ version)?  Mac OS 10.12.6
* Which layout mode? Not sure
* Which threading mode? Conversation mode
* Can you reproduce the problem each time? Yes
* Which url? https://mail.protonmail.com/inbox

### What steps will reproduce the problem?

* 1) Send a message to person A with subject X
* 2) Send a message to person B with subject X
* 3) Have both A and B respond
* 4) In the webmail UI, both conversations are grouped under the same conversation.

### What is the expected result?
The two conversations should be grouped separately. Convsersations should be grouped by set of participants and subject, not subject alone.

### What happens instead?
In the webmail UI, both conversations are grouped under the same conversation.

**Comment by vimpunk** [comment]
I noticed this too. I was rather confused to see completely different conversations grouped together before I realized what's going on. I'd be nice if this were changed.

**Comment by bartbutler** [comment]
Hmmm, that sounds like a bug unless the respondents stripped the threading headers. Which mail provider were the respondents using?

**Comment by wskinner** [comment]
@EpokK Why was this closed as invalid?

**Comment by bartbutler** [comment]
Probably because conversations are built server-side, so it's not technically a web client issue. We're looking at tweaking how we do this matching, more info here: https://www.reddit.com/r/ProtonMail/comments/90c2t7/potentially_dangerous_bug_just_happened_to_me_an/
