### ISSUE TITLE
 ReferenceError: i18nLoader is not defined

### ISSUE THREAD

**Issue by ghost** [ProtonMail/WebClients#58]
* Which browser (+ version) ? Any.
* Which OS (+ version)? Linux, Ubuntu 16.04 LTS.
* Can you reproduce the problem each time? Yes 

### What steps will reproduce the problem?

* 1) npm install
* 2) npm start

### What is the expected result?
Installing the npm packages and starting the project

### What happens instead?
Not installing all packages, and fails to start.
### Please provide any additional information below. Attach a screenshot if possible.
```
root@ubuntu-s-1vcpu-3gb-nyc3-01:~/mail/WebClient# npm start

> protonmail-web@3.12.3 start /root/mail/WebClient
> grunt watch

Loading "Gruntfile.js" tasks...ERROR
>> ReferenceError: i18nLoader is not defined
Warning: Task "watch" not found. Use --force to continue.

Aborted due to warnings.
npm ERR! code ELIFECYCLE
npm ERR! errno 3
npm ERR! protonmail-web@3.12.3 start: `grunt watch`
npm ERR! Exit status 3
npm ERR!
npm ERR! Failed at the protonmail-web@3.12.3 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-11-23T07_44_06_135Z-debug.log

```

**Comment by dhoko** [comment]
WTF, I don't understand why but it seems something went wrong during the sync of the repo :/
I fixed it -> https://github.com/ProtonMail/WebClient/commit/a9328648c5c8b3108c9b8c514bf2276f7c4bc651
