### ISSUE TITLE
Optimization - Conversation

### ISSUE THREAD

**Issue by Super-Baleine** [ProtonMail/WebClients#6]
Yahallo x)

When i have a conversation with more than 7 nay 10 emails (ah, also, my PC is old...), the loading is soooo long...
So, it's because all emails are decrypted in the same time ?

We cannot decrypt the email(s) that we selected to optimize the performances ?
:whale:

**Comment by EpokK** [comment]
When the user open a conversation we decrypt only one message. Then if he select an other message, we call the API to get the encrypted content and display it.

**Comment by Super-Baleine** [comment]
Ahnw okay, perhaps that's because my PC is old...

**Comment by EpokK** [comment]
@Super-Baleine Nous sommes en phase d'optimization sur l'application web. Les lenteurs que tu ressens devraient êtres fixées dans les prochaines semaines.

**Comment by Super-Baleine** [comment]
oh, cool ! ! :whale:

Merci pour votre travail ! x)

**Comment by Super-Baleine** [comment]
Ah, j'en profite pour rapporter une autre petite chose : 

Quand je clique sur un onglet autre que celui où j'ai ouvert PM, ça switch vite, mais lorsque je clique sur l'onglet où il y a mail.protonmail.com, ça met beaucoup de temps, hmm, genre 3 secondes, voire plus.

En fait, ça le fait sous Firefox, je suis sous Firefox 47.0.1, Debian Jessie update 5, sous Chromium je n'ai pas ce problème.

Il y a quelque chose à faire là-dessus tu penses ?

**Comment by EpokK** [comment]
Tu peux ouvrir une issue dessus stp avec le maximum de détails. En anglais stp.

**Comment by Super-Baleine** [comment]
K
