### ISSUE TITLE
Missing repo in package.json

### ISSUE THREAD

**Issue by szepeviktor** [ProtonMail/WebClients#60]
Please see https://github.com/ProtonMail/WebClient/blob/public/package.json#L4

It refers to a non-existent repo.

**Comment by szepeviktor** [comment]
@EpokK Please reconsider fixing it.

**Comment by dhoko** [comment]
Don't worry the fix is coming :) It's a post merge close.

**Comment by szepeviktor** [comment]
If you add `Closes: #60` in your commit message then the issue will be auto-closed!
