### ISSUE TITLE
Bad colors on dark themes

### ISSUE THREAD

**Issue by Ceda-EI** [ProtonMail/WebClients#68]
* Browser + version? Firefox
* OS + version? Arch Linux
* Can you reproduce the problem each time? Yes
* URL?https://mail.protonmail.com/

### What steps will reproduce the problem?

* 1) Set your firefox, qt and gtk themes to dark versions of themes. 
* 2) Press the compose button.

### What is the expected result?
The text and the background are of contrasting colors. 
### What happens instead?
The text and the background are of almost same color making the text practically invisible. This is true for other text inputs like the signature block
### Please provide any additional information below. Attach a screenshot if possible.
![screenshot-2018-02-15--11 39 38](https://user-images.githubusercontent.com/19731116/36243115-eb3794a2-1245-11e8-8a72-a0a6ad2e8d85.png)

**Comment by Ceda-EI** [comment]
This issue should be easily fixable by adding background-color to text inputs and text areas.

**Comment by jasonstockman** [comment]
@Ceda-EI I don't have a Linux environment to test this with. I ended up installing the Dark Theme in Firefox on my mac and logged in, clicked the compose button etc, but it's showing the normal composer with our defined white background and dark text.

If this only applies to Linux users who go out of their way to customize their theme for their OS and browser, I don't think this is something we should focus on. Such users could edit the ProtonMail CSS in the Appearance tab to add a few lines to customize the composer if they want to.

Until I can replicate this I can't look further into it, but my concern is that there is no way to "detect" when a dark theme is being used. Unless we can detect this, we can't add an exception or special code to make these color changes without having them always exist. We don't want a black background and white text for all users so unless we can somehow detect this special case, we can't do much about all of this.

Is this something I can replicate on Mac?

**Comment by Ceda-EI** [comment]
>  Such users could edit the ProtonMail CSS in the Appearance tab to add a few lines to customize the composer if they want to.

Could you provide the CSS? That would be a very helpful workaround.

> Until I can replicate this I can't look further into it, but my concern is that there is no way to "detect" when a dark theme is being used.

This issue probably appears because the background-color might not be set and as such the browser defaults to the default color. Setting a background-color might solve the issue.

> Is this something I can replicate on Mac?

I do not use a Mac so I have no idea about that.

**Comment by EpokK** [comment]
Fixed, wil be available in the next release.

**Comment by proof-by-accident** [comment]
~~Hi All, apologies for resurrecting a dead issue. I'm having the same problem using a custom Firefox userChrome.css. Would anyone be able to point me towards the right CSS element to modify in the theme to correct this problem?~~

Please disregard, I was able to fix the conflicting lines in the userContent.css file.
