### ISSUE TITLE
No red banner for missing DKIM record

### ISSUE THREAD

**Issue by szepeviktor** [ProtonMail/WebClients#69]
Hello!

I'm testing DKIM signing on my server. When DKIM/SPf is broken Protonmail displays a red banner saying *DANGER! Tampering* (not exactly word-by-word)

> Authentication-Results: mail9i.protonmail.ch; dkim=fail reason="key not found in DNS"
>  (0-bit key) header.d=tarhelywordpress.hu header.i=@tarhelywordpress.hu
> header.b="evJr8AcO"

With this result - no DKIM record in DNS - I get no red banner.
Please advise.

* Browser + version? Firefox + strict settings
* OS + version? Windows 10 Pro 64 bit
* Can you reproduce the problem each time? Yes
* URL? https://mail.protonmail.com/inbox/kmH83ZvyPJHw3nJMFyZT8ERyjTsXFPvctepYRnkm9d2cisPaK5hkTP9wfa-IU9dSwzsLoH6ChI2f1C7PJufNcA==

### What steps will reproduce the problem?

* 1) Do not add DKIM record to DNS
* 2) Sign mail
* 3) Receive it in Protonmail

**Comment by dingchaolu** [comment]
The warning banner depends on whether your dmarc fails or not. You can read more about how dmarc relates to spf/dkim here: https://protonmail.com/support/knowledge-base/anti-spoofing/

**Comment by szepeviktor** [comment]
So existing DKIM signature + missing DNS record is not a red warning.
Am I right?
