### ISSUE TITLE
Long delay

### ISSUE THREAD

**Issue by Super-Baleine** [ProtonMail/WebClients#7]
Yahallo, :whale: 

When i switch tab to a random website, it's fast. But, when i switch to the mail.protonmail.ch tab, is long (2,3 seconds). I cant give more details... It's all.

On Chromium, it works normally.

I'm on Firefox, 47.0.1, Debian Jessie Update 5.

**Comment by EpokK** [comment]
We are working actively to optimize the web application performance, you should feel the difference with the next releases.
