### ISSUE TITLE
User-Agent: header

### ISSUE THREAD

**Issue by szepeviktor** [ProtonMail/WebClients#70]
Could you add

`User-Agent: ProtonMail` to every message composed by ProtonMail?

**Comment by bartbutler** [comment]
Where? We do add something similar in the OpenPGP armor but in most cases this isn't seen by users.

**Comment by szepeviktor** [comment]
In the email headers.
Of course it is not displayed in a normal email client!

**Comment by szepeviktor** [comment]
e.g. Horder adds the `User-Agent` header

**Comment by bartbutler** [comment]
Why should this be done? As far as I can tell this is completely optional (and non-standard) usage.

**Comment by szepeviktor** [comment]
You're right, it should not be done, it is a proposal.
