### ISSUE TITLE
Lack of New/Planned Features

### ISSUE THREAD

**Issue by szepeviktor** [ProtonMail/WebClients#71]
Hello!

Could it be that various new features are planned but not implemented month-by-month?
I am not into listing those features here.

**Comment by szepeviktor** [comment]
@EpokK @Swiip All open issues were closed just now.
What does it mean to the project? Is it over?

**Comment by NishaYume** [comment]
What happens

**Comment by mmso** [comment]
Feature requests are welcome at https://protonmail.uservoice.com/forums/284483-protonmail
