### ISSUE TITLE
Selecting messages

### ISSUE THREAD

**Issue by szepeviktor** [ProtonMail/WebClients#72]
Hello!

Do you plan implement message selection with <kbd>Ctrl</kbd> + click (single on/off) and <kbd>Shift</kbd> + click (range selection)? Maybe <kbd>Shift</kbd> + <kbd>⬇️</kbd> or up.

**Comment by Rafficer** [comment]
Works more or less, you just have to click on the checkboxes and not on the mail.

**Comment by szepeviktor** [comment]
Thank you.

I am a 10+ years Horde user.
