### ISSUE TITLE
Free accounts can add picture to contacts

### ISSUE THREAD

**Issue by Rafficer** [ProtonMail/WebClients#74]
* Browser + version? Firefox 59.0.2
* OS + version? Windows 10 Edu (1709 Build 16299.309)
* Can you reproduce the problem each time? YYes
* URL? https://mail.protonmail.com/contacts

### What steps will reproduce the problem?

* 1) Go to a contact with a free account
* 2) Select the contact and choose "edit photo" below the "upgrade now" window

### What is the expected result?

The button shouldn't be clickable in the first place

### What happens instead?

It works.

### Please provide any additional information below. Attach a screenshot if possible.

https://i.imgur.com/xHzjD3B.gifv

**Comment by EpokK** [comment]
Fixed.
