### ISSUE TITLE
UI-string mismatch: "Labels /  Folders" vs " Folders / Labels"

### ISSUE THREAD

**Issue by sveinki** [ProtonMail/WebClients#76]
* In the source code + translation files.

On line 29 in the wizard  WebClient/src/templates/partials/wizard.tpl.html we have: "Labels are a powerful tool to manage your inbox. You can add and remove labels from selected emails by clicking the Label button <strong>(1)</strong>. You can also add, delete, and edit labels by clicking on <em>Labels / 
Folders</em> <strong>(2)</strong>."
You can't click on "Labels / Folders" because the button is labeled "Folders / Labels", at least the instances I've found (f.x. in  WebClient/src/templates/partials/sidebar.tpl.html, line 24).
I think this should be synchronized ASAP.

**Comment by sveinki** [comment]
I've found similar mismatches for "Report bugs" vs "Report bug" and "Users/Addresses" vs "Addresses / Users"; should those be seperate issues?

**Comment by EpokK** [comment]
Fixed in the next version.
