### ISSUE TITLE
Can't view or can't hide email on mobile

### ISSUE THREAD

**Issue by JulienPalard** [ProtonMail/WebClients#78]
* Mozilla Fennec — Firefox 59.0.2 on a Nexus 6P
* LineageOS 15.1-20180430-NIGHTLY-angler — Android 8.1.0
* Can you reproduce the problem each time? Yes
* mail.protonmail.com

### What steps will reproduce the problem?

* 1) Open https://mail.protonmail.com on Android on Firefox 59.0.2
* 2) Touch an email to open it (Single mail, not a conversation)
* 3) Either the mail opens, and by touching the header it won't close
* 3bis) Either the mail won't open (only header) and touching the header won't open it

Actualy it's more than a "double toggle" than a "won't close" or "won't open" as it blinks.

### What is the expected result?

No double toggle on touch, only toggle (hide if shown, show if hidden)

### What happens instead?

Double toggle happen on touch: show-hide when hidden, and hide-show when shown.

**Comment by EpokK** [comment]
If you open one mail, the only way to close it, is to touch the back icon present on the top left.
