### ISSUE TITLE
Wrong count of emails

### ISSUE THREAD

**Issue by JulienPalard** [ProtonMail/WebClients#79]
* Firefox 59.0.2
* Debian Buster
* Sometimes it happen, sometimes not.
* https://mail.protonmail.com/inbox

### What steps will reproduce the problem?

* 1) Look for unread messages in folders
* 2) Click on the folder
* 3) See that the folder is sometimes empty
* 4) Click on refresh near the folder name (Does not fix the issue)
* 4) Ctrl-F5 (big refresh)
* 5) Still the same `(1)` near `Spam`, still no mail in spam.

### What is the expected result?

If I see "Spam (1)" I expect one unread mail in my spam folder.

### What happens instead?

No spam (True story).

### Please provide any additional information below. Attach a screenshot if possible.

![protonmail](https://user-images.githubusercontent.com/239510/39667498-0ec907ce-50b8-11e8-9d9c-baa8b5cf074e.png)

**Comment by bartbutler** [comment]
This is probably a server-side issue with caching. Can you provide me with an account name exhibiting this problem so I can look into it?

**Comment by JulienPalard** [comment]
Hi @bartbutler thanks for looking at it, my account is `julien@palard.fr`.

**Comment by JulienPalard** [comment]
Got the issue again today: protonmail is telling me I'm having one unread message in my `py` folder, containing two conversation fully read:

![protonmail-unread](https://user-images.githubusercontent.com/239510/42379297-8ba75be0-812a-11e8-820e-4d7bc373d311.png)

**Comment by bartbutler** [comment]
Thanks @JulienPalard I'll take a look right now.

**Comment by bartbutler** [comment]
@JulienPalard are you still seeing it or did it resolve itself? I'm seeing zero from my end.

**Comment by JulienPalard** [comment]
It resolved itself quickly, typically with a refresh of the page, or by clicking on already read threads, but it happen from times to times, I'm not posting a screenshot each time.

**Comment by bartbutler** [comment]
Understood.

**Comment by JulienPalard** [comment]
Got the error right now while emptying my spam folder while counting the seconds between the mouse click and the value being updated, it took 30s for the number to disapear.

**Comment by vallode** [comment]
I've seen a similar issue on my side, at times when I read a message the folder unread count will take a little while to disappear.
