### ISSUE TITLE
Mobile (Android) client synchronization 

### ISSUE THREAD

**Issue by c1tt1** [ProtonMail/WebClients#81]
* OS Android

On mobile at least on Android, (can't speak for iOS) there is a synchronization problem with the web client.
When there is a new email read by the web client the android client doesn't sync with it and thus when connected to the internet it still notifies you with a new email, while the email has been read with the web client.

The other way round is fine in the sense that when you read a new email with the android client the web client syncs with it.

It would be good to have the android client sync with all activities by the user even on different clients.

**Comment by mtimofiiv** [comment]
Yes, the push notifications are a little annoying since they happen despite the email for them already being deleted.

**Comment by EpokK** [comment]
There is actually a delay of 30 seconds between clients to synchronize events.
