### ISSUE TITLE
email links do not fill subject, body and other mailto attributes

### ISSUE THREAD

**Issue by lypwig** [ProtonMail/WebClients#82]
* Browser + version: Frefox 60
* OS + version: Ubutnu Mate 17.10
* Can you reproduce the problem each time? Yes

### What steps will reproduce the problem?

1. Send a mail to your own address with a link to this url: `test@example.com?subject=foo&body=bar`

### What is the expected result?

If I click on the link to the received mail, ProtonMail should create a new mail, with the Subject field filled with `foo`, and the Body text area filled with `bar`.

### What happens instead?

Subject and Body are empty.

### Please provide any additional information below. Attach a screenshot if possible.

See for example [this page](https://yoast.com/dev-blog/guide-mailto-links/) about mailto syntax. Note that `cc` and `bcc` attributes should also work.

**Comment by lypwig** [comment]
Why did you closed this @EpokK, this is not going to be fixed?

**Comment by dhoko** [comment]
It's because of the auto-close feature from github ;) We merged a PR with this fix.
