### ISSUE TITLE
"Conversation does not exist" error message when deleting

### ISSUE THREAD

**Issue by 0joshuaolson1** [ProtonMail/WebClients#88]
On Chrome 67 (Debian Linux 64 bit), I've seen the `Conversation does not exist` error message sometimes when deleting an email, at least from the inbox (is it just moving?) and from the trash.

Of course it shouldn't exist.

**Comment by Username123456765645** [comment]
Does the su happen on any other device do you have

**Comment by 0joshuaolson1** [comment]
I don't see this bug on my Android device, even in desktop view.

**Comment by EpokK** [comment]
Should be solved with `3.14.4`.
