### ISSUE TITLE
[Android app] a bit slow to open mails

### ISSUE THREAD

**Issue by JulienPalard** [ProtonMail/WebClients#89]
* OS + version? Android 8.1 on Nexus 6P
* Can you reproduce the problem each time? Yes

### What steps will reproduce the problem?

* 1) Open a mail by touching it

### What is the expected result?

Mail to open.

### What happens instead?

Mail is a bit slow to show up.

### Please provide any additional information below. Attach a screenshot if possible.

![https://mdk.fr/protonmail.webm](https://mdk.fr/protonmail.webm) (copy / paste https://mdk.fr/protonmail.webm link in new tab if don't show up)

**Comment by Rafficer** [comment]
I think it's better to open a ticket with their support team via https://protonmail.com/support-form. This repository is for the webclient and not the android app, the app is not open-source, yet.

**Comment by JulienPalard** [comment]
Yes I know :) But I opened way too many bugs via support-form, and it's impossible to track them. So I decided to "squat" here from now.

Best solution I think would be to for them to create the project on github, even without uploading the source code, just to properly organize issues.

**Comment by Username123456765645** [comment]
I don't know why the Android application is not open source

**Comment by EpokK** [comment]
Reported to mobile team.

**Comment by JulienPalard** [comment]
@EpokK Can you please create the project (for the mobile apps) on github so we could at least start to report issues there, even if you don't upload the code yet?
