### ISSUE TITLE
mailto links not parsing encoded characters, not parsing parameters at all on Android app

### ISSUE THREAD

**Issue by euphemism** [ProtonMail/WebClients#91]
* Browser + version? Firefox 61.0.1, Edge 42.17692.1004.0
* OS + version? Windows / Android
* Can you reproduce the problem each time? Yes

### What steps will reproduce the problem?

1) Create a mailto link with several parameters (address/subject/body etc.)

 * i.e. mailto:person@example.com?subject=RE:%20Email%20Subject&body=%0D%0A%0D%0A--%0D%0A%20message
2) Encode characters as needed (spaces to %20 line breaks to %0D%0A etc.)
3) Send this to a ProtonMail address.
4) Open the email in the ProtonMail client and hover over/click the link.

### What is the expected result?
* A new email should open in the composition window, with the expected fields already filled out, and the encoded characters parsed back into their original forms.
* This same mailto link works as expected when sent to non-ProtonMail addresses and opened in other clients.

![mailtooutlook](https://user-images.githubusercontent.com/1179754/42662422-2d839ade-85f7-11e8-83e8-cb1660dd6261.png)
![mailtowindows](https://user-images.githubusercontent.com/1179754/42662423-2d9ca9e8-85f7-11e8-9937-2582788ab930.png)

### What happens instead?
* In Firefox, hovering over the link shows in the link preview that the encoded spaces are parsed as space characters.  In Edge, hovering over the link shows in the link preview the encoded spaces.  In both, the line breaks remain shown as encoded in the preview.  This may not be a ProtonMail issue and instead is a browser thing.  I don't know.
* Clicking on the mailto link opens up the composition window.  In Edge, the fields are populated, but the encoded characters are not parsed and converted into their original forms.  ![mailtoedge](https://user-images.githubusercontent.com/1179754/42662420-2d56e034-85f7-11e8-9168-957d932e545b.png)

In Firefox, the _To_ field is populated with the address, but the subject and body are empty.  ![mailtofirefox](https://user-images.githubusercontent.com/1179754/42662421-2d6c6c10-85f7-11e8-82d4-7c96f650bda3.png)

* The Android client doesn't even seem to try.  Clicking the link just opens up a completely blank email in the composition window.

**Comment by dhoko** [comment]
The fix is coming soon :) Thx for the issue :+1:
