### ISSUE TITLE
Message-ID contain quoted-printable encoded words

### ISSUE THREAD

**Issue by emersion** [ProtonMail/WebClients#93]
This is not strictly a WebClient bug report, but rather a backend bug report.

One of my email's recipients recently noticed ProtonMail is sending quoted-printable encoded `Message-ID` headers [1]. It looks like this:

```
Message-ID: =?utf-8?q?=3CwJ6Gixv2LKcZ9Gsu3OPG3UQYBNFbsSoJC79LXjCmEEV1bmhxI74?=
 =?utf-8?q?hqauM26AMFfIaih1MrukUrJhF---575PI5q4J6Eq5UiVHHfIYBuCB8SA=3D=40eme?=
 =?utf-8?q?rsion=2Efr=3E?=
```

However per [RFC 5322][2] this is incorrect. The grammar specifies:

```
message-id      =   "Message-ID:" msg-id CRLF
msg-id          =   [CFWS] "<" id-left "@" id-right ">" [CFWS]
```

[RFC 2047 section 6.1][3] states conditions in which a header field can contain encoded words, and the `Message-ID` field does not qualify.

This causes issues with other email clients, which ignore the `Message-ID` field, thus the `In-Reply-To` field is not set when they reply and that breaks the threading on their end.

[1]: https://gitlab.com/muttmua/mutt/issues/60
[2]: https://tools.ietf.org/html/rfc5322
[3]: https://tools.ietf.org/html/rfc2047#section-6.1

**Comment by bartbutler** [comment]
I can't reproduce this, can you? My theory is that the quoting is being done by some mailing list software somewhere before it reaches the final recipient.

**Comment by ddevault** [comment]
Maintainer of said mailing list here. Looking into that possibility now.

**Comment by ddevault** [comment]
Yep. It does a round-trip through the Python email parser and I needed an extra flag to prevent the header from being mangled. Fixed on my end.

**Comment by emersion** [comment]
Thanks for taking the time to investigate, and sorry for this bug report!

**Comment by bartbutler** [comment]
Excellent, closing the issue.
