### ISSUE TITLE
'Trash' button in notification bar doesn't work. 

### ISSUE THREAD

**Issue by ghost** [ProtonMail/WebClients#94]
## Expected Behavior
When receiving and email and getting the notification in the notification bar and then click on the 'Trash' button it should delete the email. 

## Actual Behavior
Clicking the 'Trash' button on the notification bar does nothing. 

## Steps to Reproduce the Problem

  1. Receive an email. 
  2. Click 'Trash' button. 
  3.

## Specifications

  - Version: 1.9.2
  - Platform: Android.
  - URL:

**Comment by EpokK** [comment]
Reported to mobile team.
