### ISSUE TITLE
Conversation greyed out even when containing a new email.

### ISSUE THREAD

**Issue by JulienPalard** [ProtonMail/WebClients#96]
This is the counterpart of #79 :

I'm having a folder, `github`, which was marked with a `(1)` but by clicking on it to open this folder, all conversations (only 5 conversations) were displayed "grey" (meaning: no new mail in the converation) not "black and white" (meaning : there's an unread email in this thread).
 
I had to click on all conversations to see which one (the last one obviously, the one on the top, but I started from the bottom) to see which one contained a new message. I was more seraching for a way to drop the `(1)` than to find an unread messages, as I though I faced issue #79 at first.

**Desktop (please complete the following information):**
 - OS: Debian
 - Browser Firefox
 - Version 61.0.1
 - URL mail.protonmail.com

**Comment by bartbutler** [comment]
So in this case the (1) was correct  but the conversation highlighting was off?

**Comment by JulienPalard** [comment]
Yes the `(1)` was right as far as I can tell [1], but the conversation was not highlited properly, it was grey like a conversation with no unread messages.

[1]: My brain first expected #79 when I spotted it so there's a little chance I got confused. Very little but existing, I should video-capture everything þ

**Comment by JulienPalard** [comment]
Got the bug today again, with a screenshot this time:
![bug-protonmail](https://user-images.githubusercontent.com/239510/44038806-e8c83eb0-9f17-11e8-80ad-37ee007b7d50.png)

Here's the `(1)` near `github` is right, I'm having one unread email in the `OsmAnd is slow on Android O` conversation.

While opening this conversation, the `(1)` next to `github` dissapeared while the last mail (the unread one) showed-up.

**Comment by bartbutler** [comment]
Ignoring the sidebar count for a moment, was the unread message in the github folder or in inbox? I ask because conversations can include messages from different folders, whereas the sidebar just counts unread for that folder/label, i.e., they are context dependent. So you could have a conversation with an unread message in inbox, all messages in 'github' read, and it would show up as grey (no unread messages) in the github folder listing.

**Comment by JulienPalard** [comment]
The unread message was the last one of a "thread" of emails in the github folder.

> So you could have a conversation with an unread message in inbox, all messages in 'github' read, and it would show up as grey (no unread messages) in the github folder listing.

I don't think it's my case as my `github` folder is a part of my sieve filter:

```
[...]
elsif header :contains "list-id" ".github.com>" {
    fileinto "github";
}
[...]
```

Yes, I ocasionally move emails from my github folder to my inbox (a way for me to "mark them as TODO" / to make them more visible when I have something to do with them), but I don't mark them as unread when I do, and I had nothing "todo" with this email, so it can't be the case.

**Comment by bartbutler** [comment]
OK, just wanted to make sure.

**Comment by JulienPalard** [comment]
Spotted it again today with a specific configuration: 
- The thread was all in the `Trash` directory
- Except for the unread email which was in the `github` directory.
- The conversation was showing in the github directory, greyed as when read (which was wrong), marked as containing 3 emails, and containing the icons of the directory and the icon of the trash (all right).
- When clicking the conversation, the single non-trashed unread email showed up, correctly prefixed by a "This conversation contains trashed messages", the `(1)` unread flag correctly dissapeared.

I do not exclude that all previous cases were similar (whole conversation in trash except a single unread email in folder).

**Comment by EpokK** [comment]
This report seems a duplicate from: https://github.com/ProtonMail/WebClient/issues/79

About this report: https://github.com/ProtonMail/WebClient/issues/96#issuecomment-413495574

@JulienPalard `Unread` counter is specific per folder. So if you have a thread in `Trash` and one of the message is unread and is in `github` folder, unread counter equals `0` for this conversation. 

If you go to `github` folder and check this conversation, then it will be marked as unread.

**Comment by JulienPalard** [comment]
Hi @EpokK, I do not understand the `wontfix` label, my experience is:

- Open mailbox
- See folder with `(1)` unread message, click on it.
- See 10 conversations, no conversation are maked with unread message, have to click on every one of them to find the hidden unread message.

Can this really be considered a feature? From my user experience, it's clearly a problem.

see: ![](https://user-images.githubusercontent.com/239510/44038806-e8c83eb0-9f17-11e8-80ad-37ee007b7d50.png)
