### ISSUE TITLE
Why does "Move to trash" imply "Mark as read"?

### ISSUE THREAD

**Issue by dmtucker** [ProtonMail/WebClients#98]
**Describe the bug**
Moving to the trash implicitly marks a message as read.

**To Reproduce**
1. Check an unread message.
2. Click on "Move to trash".
3. Open the Trash.
4. See the message marked as read.

**Expected behavior**
If I have never read a message (or marked it read), then that message remains marked unread.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Debian 9
 - Browser: Firefox ESR
 - Version: 52.9.0
 - URL: https://mail.protonmail.com/

**Smartphone (please complete the following information):**
 - Device: Pixel 2 XL
 - OS: Android 8.1.0
 - Browser: N/A (app)
 - Version: 1.9.1

**Comment by bartbutler** [comment]
Thanks for your report. This is intended. We used to get dozens of complaints per month that people found unread messages in their trash annoying. So we made trashing messages mark them unread automatically. Yours is the first complaint about this we have received since we did it, maybe a year or more ago.

**Comment by dmtucker** [comment]
@bartbutler, can we convert this into a feature request to make it (either auto-marking read or hiding the unread count) configurable then?

**Comment by bartbutler** [comment]
Sure. No promises, but we will discuss it.

**Comment by dmtucker** [comment]
The "Move to trash" button should probably say "Mark as read and move to trash" in the meantime...

**Comment by dmtucker** [comment]
Any updates on this?

**Comment by dmtucker** [comment]
For future readers, this was NOT delivered. I assume it should have been marked `wontfix` instead of `completed`.
